### PR TITLE
Changes to #2298

### PR DESCRIPTION
**Pull request by kwalrath**
Fixes the build. Note that some code snippets in the page still don't have excerpts.

Staged:
https://kw-www-dartlang-1.firebaseapp.com/codelabs/dart-cheatsheet

### CODE REVIEW

**Comment by kwalrath** [comment]
@jddeep how would you like to proceed?

**Comment by jddeep** [comment]
@kwalrath should I go ahead and patch the changes after my commits to #2298 Thanks:)

**Comment by jddeep** [comment]
https://github.com/dart-lang/site-www/pull/2298#issuecomment-596047870

**Comment by johnpryan** [comment]
LGTM

@jddeep We can merge this PR as-is (you will still get authorship on the squashed commit) or you could you merge this PR into #2298 and we will merge that one. We'd prefer to keep the build passing if possible. Thanks!

**Comment by jddeep** [comment]
Updated https://github.com/dart-lang/site-www/pull/2298

**Pull request closed without merging**
