### PR TITLE
Added new dart book

### PR DESCRIPTION
**Pull request by MADTeacher**
Added information about the new book on Dart. The material is relevant for Dart 3.4

### CODE REVIEW

**Comment by atsansone** [comment]
Summary translates as:

_The book "Basics of Dart" is addressed to those who are interested in this amazing programming language. You'll learn about the language's history, syntax, and features such as built-in data types, and much more. In Chapter 2 you will find a project that will change and grow with your knowledge and skills, and by Chapter 6 it will transform into a full-fledged client-server application. After each new iteration of the project, you will receive proposals to make changes to its code base, which will allow you to improve your hard skills. The source code for the examples discussed in the book can be found in the author's GitHub repository (all code in the book complies with Dart 3.4)._

**Comment by atsansone** [comment]
@MADTeacher : Happy to accept this submission, but you need to sign the CLA first. Thanks!

**Comment by MADTeacher** [comment]
@atsansone Thanks! I am signed the CLA

**Review by atsansone — APPROVED** [review]
LGTM!

**Pull request merged**
