### PR TITLE
[site-www] Code-excerpts for Codelabs Cheatsheets

### LINKED ISSUE #2295: Add and auto-include cheatsheet code samples
We need to add the cheatsheet code samples in the repo so that we can link the code-excerpts in the source file.

Context: #1803 

cc: @kwalrath

### PR DESCRIPTION
**Pull request by jddeep**
[site-www] Code-excerpts for Codelabs Cheatsheets

Fixes #2295 
Context #1803 

cc: @kwalrath

### CODE REVIEW

**Comment by kwalrath** [comment]
For the build and auto-inclusion to work, we need docregion comments in the .dart files code snippets in the .md file. The regions don't have to be named if there's only one example in the file. For example, see [dcat1.dart](https://github.com/dart-lang/site-www/blob/master/examples/misc/bin/dcat1.dart), which uses just `// #docregion` to mark the start of included code. Add `// #enddocregion` to mark the end of the included code (if necessary).

For an example with named regions, you add the region name. For example, see [dcat.dart](https://github.com/dart-lang/site-www/blob/master/examples/misc/bin/dcat.dart), which has code like the following:

```
// #docregion arg-processing
ArgResults argResults;
// #enddocregion arg-processing
```

**Comment by jddeep** [comment]
@kwalrath Have a look now, please.

**Comment by kwalrath** [comment]
I've made some changes that should fix the build, but I might not have the git fu necessary to add them to this PR. See #2301 for my changes.

**Comment by kwalrath** [comment]
@jddeep it looks like you're doing the changes one-at-a-time in the GitHub UI. Have you tried getting the build to work locally? (I think it works on Mac & Linux, but not Windows.)

**Comment by jddeep** [comment]
@kwalrath Yes, i was using the Github features for these changes. Although i do have Linux set up locally, will definitely try to get the build up and running locally. Thanks.

**Comment by jddeep** [comment]
@kwalrath Should I patch the changes from #2301 to here myself or you could merge this and then merge #2301 on top of this with your updating commits. Do let me know. Thanks.

**Comment by kwalrath** [comment]
Sorry, just saw this. Could you please patch the changes from #2301 to here?

**Comment by jddeep** [comment]
@kwalrath @johnpryan Good to go!

**Comment by kwalrath** [comment]
Merged, thank you @jddeep! I reopened the bug because I believe there are still some more excerpts to be analyzed, but this PR goes a long way toward fixing the issue.

**Pull request merged**
