### PR TITLE
change the code snippet

### PR DESCRIPTION
**Pull request by Abhishek01039**
fixes https://github.com/dart-lang/site-www/issues/2790

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@kwalrath 
are these colors is ok or should I use a different color?
Thanks

**Comment by kwalrath** [comment]
Unfortunately, that approach won't work because we need to compare against working code excerpts.

I'd probably use a combination of comments (duplicated in the .md file and the code excerpts' .dart files) and moving down the "bad" code marker for the second example. And... looking closer... there's the issue that the "bad" code doesn't actually work, which is why we disconnected it from the code excerpt system. Maybe I shouldn't have marked this as beginner. :) 

Can you come up with a "bad" excerpt that passes analysis but illustrates the problem? If not, then maybe this rule is no longer needed?

**Comment by kwalrath** [comment]
/cc @munificent 
The affected rule is https://dart.dev/guides/language/effective-dart/design#do-annotate-when-dart-infers-the-wrong-type.

**Comment by Abhishek01039** [comment]
ok @kwalrath 
I will find the example and add it here!
Thanks

**Comment by kwalrath** [comment]
Actually... We need to stop work on this page. @munificent is about to make a pass through Effective Dart, so we need to avoid modifying those docs for a while.

Sorry for the churn! Maybe you could work on one of the pages under #2617?

**Pull request closed without merging**
