### PR TITLE
Use HTTPS in links when possible

### PR DESCRIPTION
**Pull request by jonasfj**
Just a lot of nits upgrading HTTP to HTTPS links whenever possible.

I found one or two links that didn't work or which seemed broken, so I left those alone.

### CODE REVIEW

**Comment by kwalrath** [comment]
The problem is that examples/misc/lib/effective_dart/docs_good.dart needs to be updated to use https instead of http. I can't do that through the GitHub interface (afaik) since you didn't edit that file.

If you can fix that file before EOD, great. If not, I'll merge this PR and then fix the build.

**Comment by kwalrath** [comment]
It looks like @jonasfj won't get to this, so I'll merge this and then commit a PR to fix the build and #2072.

**Comment by jonasfj** [comment]
Sorry, I was a bit behind on my inbox.. thanks fixing it.

**Comment by kwalrath** [comment]
No worries, it was easy.

**Pull request merged**
