### PR TITLE
add rethrow;

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
Fixes https://github.com/dart-lang/site-www/issues/6047

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn't contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn't use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/packages/excerpter) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Comment by AbdeMohlbi** [comment]
@nate-thegrate

**Comment by sfshaza2** [comment]
@domesticmouse, can you confirm this code change?

**Review by nate-thegrate — APPROVED** [review]
Beautiful ❤️

**Comment by nate-thegrate** [comment]
@AbdeMohlbi it looks like being a member of [flutter-hackers](https://github.com/flutter/flutter/blob/master/docs/contributing/Contributor-access.md) unfortunately doesn't give me commit access here, so you'll have to wait for someone else to review.

<br>

For @domesticmouse and/or other reviewer(s): [previous discussion](https://github.com/dart-lang/site-www/pull/6048) for context

**Comment by AbdeMohlbi** [comment]
> @AbdeMohlbi it looks like being a member of [flutter-hackers](https://github.com/flutter/flutter/blob/master/docs/contributing/Contributor-access.md) unfortunately doesn't give me commit access here, so you'll have to wait for someone else to review.
> 
> <br>
> 
> For @domesticmouse and/or other reviewer(s): [previous discussion](https://github.com/dart-lang/site-www/pull/6048) for context

No problem man just want to asure i'm on the right path

**Comment by nate-thegrate** [comment]
I'm curious… why did this get closed? I think it's a good change.

**Pull request closed without merging**
