### PR TITLE
Update side-nav.yml

### PR DESCRIPTION
**Pull request by devoncarew**
- reorder the `Editors & debuggers` section of the sitenav

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks! Looks like I don't have permission to merge myself.

**Comment by johnpryan** [comment]
I'm not sure why that is - FYI @kwalrath

**Comment by kwalrath** [comment]
> Thanks! Looks like I don't have permission to merge myself.

That’s weird. Everyone in Dart Core Eng has Write permission, which I’d think would be sufficient.

**Comment by devoncarew** [comment]
There may be an additional check in the admin page? It was a 'can't merge' message that I hadn't seen before.

**Pull request merged**
