### PR TITLE
Add missing type annotations

### PR DESCRIPTION
**Pull request by komainu8**
Hello,

I suppose that this example sets the types better than omit the types.
Because Dart recommends type annotations.

I just started studying Dart. So, this PR maybe not a good...

thanks,

### CODE REVIEW

**Comment by komainu8** [comment]
@googlebot I signed it!

**Comment by kwalrath** [comment]
You updated the .dart file as well as the .md file, well done! I think we'll accept your change... but I'll check. When we originally wrote the language tour, it was a selling point that you could omit types until you were ready to add them. I'm not sure how we feel about omitted types nowadays.

@mit-mit or @munificent, want to opine? This is the sample at the top of the language tour: https://dart.dev/guides/language/language-tour#a-basic-dart-program. Adding `void` would also give us a chance to mention it in the discussion just after the sample.

**Review by munificent — APPROVED** [review]
LGTM.

**Comment by kwalrath** [comment]
Thank you, @komainu8!

**Comment by komainu8** [comment]
Thank you for merge my pull request.

**Pull request merged**
