### PR TITLE
Fix Dart 2.4 banner link

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
TBR @sfshaza2

**Comment by sfshaza2** [comment]
TBR? To be read?  I had to google that and I’m still confused.  :)

**Comment by mit-mit** [comment]
Sorry for the lingo, I was referring to it in the 'To Be Reviewed (after merge)'-sense: https://github.com/flutter/flutter/wiki/Tree-hygiene#landing-a-patch-in-a-hurry-for-emergencies

**Comment by sfshaza2** [comment]
Thanks for the info/link!

**Comment by sfshaza2** [comment]
J’approve. LGTM!

**Pull request merged**
