### PR TITLE
Change src/_guides/packages to use new dart tools

### PR DESCRIPTION
**Pull request by sachin-cpp**
Fixes a part of [#2617](https://github.com/dart-lang/site-www/issues/2617) .
Changed `_src/_guides/packages.md_ ` to use _new dart tools_ .

### CODE REVIEW

**Comment by sachin-cpp** [comment]
@googlebot  I signed it!

**Review by kwalrath — COMMENTED** [review]
Thanks for the PR! We'll also need to (1) fix the link definitions and (2) update or somehow annotate the other references to pub commands in this page.

**Comment by kwalrath** [comment]
We still need to fix the link definitions. Can you finish this up, @sachin-cpp, or would you like me to take over this PR?

**Comment by sachin-cpp** [comment]
Hi @kwalrath , I apologize I was not active these days...... you can take over this PR .

**Review by kwalrath — APPROVED** [review]

**Pull request merged**
