### PR TITLE
Change MAC to macOS

### LINKED ISSUE #3137: Mac -> macOS
Per the discussion in #2892.

### PR DESCRIPTION
**Pull request by bharat-biradar**
fixes #3137

### CODE REVIEW

**Review by kwalrath — CHANGES_REQUESTED** [review]
It's a good start, but we'll need to update the code, too, to avoid having Mac in some places and macOS in others. I think updating the code will require a local copy so we can regenerate the JavaScript.

Also, even once we update the script, the issue probably needs to stay open, since there are lots of other occurrences of _Mac_ on this site.

image

**Comment by bharat-biradar** [comment]
I completely missed noticing it. I'll try to make the changes as soon as possible. Incase of any doubt I'll ask them here.

**Comment by bharat-biradar** [comment]
Could you please elaborate on what you meant by `regenerate javascript`?

**Comment by kwalrath** [comment]
> Could you please elaborate on what you meant by `regenerate javascript`?

There's some info at https://github.com/dart-lang/site-www/blob/master/src/tools/sdk/archive/_README.md.

It can take a bit of time and effort to get the local build of site-www working, so I'll understand completely if you don't want to go to the trouble!

**Comment by bharat-biradar** [comment]
Thank you. I'll take a look at the site working before deciding.

**Comment by bharat-biradar** [comment]
@kwalrath I could not figure out how to change the version table. But to the already made changes i.e `index.html` file should I regenerate the javascript as it says there that you should do it only when dart code is modified and I am changing an HTML file here. If I should I'll just regenerate the javascript and push it to the current PR so that at least this change can be completed.

**Comment by kwalrath** [comment]
I believe you'd need to modify the Dart code; otherwise, JavaScript regeneration won't do anything.

**Comment by bharat-biradar** [comment]
Then is there no need to regenerate javascript for the currently made changes? i.e in this PR.

**Pull request closed without merging**
