### PR TITLE
Fixed provably typo to probably

### PR DESCRIPTION
**Pull request by JasonJamal**

### CODE REVIEW

**Comment by JasonJamal** [comment]
@googlebot I signed it!

**Comment by mit-mit** [comment]
I believe this is actually intended; "provable" as in "can be proved", right @munificent ?

**Comment by mit-mit** [comment]
But I also seem to recall we got this feedback before, so perhaps better to rewrite?

**Comment by munificent** [comment]
Yes, I intended "provably" here. :)

**Pull request closed without merging**
