### PR TITLE
fixing equality operator typo

### PR DESCRIPTION
**Pull request by mshwf**

### CODE REVIEW

**Comment by mshwf** [comment]
@googlebot I signed it!
________________________________

**Comment by kwalrath** [comment]
Actually, that `.` was intentional, as a way of emphasizing that `==` (like all operators) is actually a method invoked on the first operand.

However, since that code doesn't actually work (and I don't know if it ever did), maybe we should put it another way.

@munificent do you have any suggestions? The relevant text is in https://dart.dev/guides/language/language-tour#equality-and-relational-operators.

**Comment by mshwf** [comment]
No way to think that, especially it's in a code styled. It's frustrating more than clarifying. However, it actually helps seeing this operator from another angle. May be put that in a note or something.

**Comment by munificent** [comment]
Yeah, I agree with Kathy, the syntax here is deliberate and I think it does clarify things for most readers.

**Comment by kwalrath** [comment]
I'm going to close this PR but open an issue describing the problem with the text, as it's written. Thank you, @mshwf, for bringing this to our attention!

**Pull request closed without merging**
