### PR TITLE
Dart language-version menu for switching between site versions

### PR DESCRIPTION
**Pull request by chalin**
Addresses https://github.com/dart-lang/site-www/issues/654#issuecomment-376715048.

Staged at https://dartlang-org-staging-0.firebaseapp.com

Feature allowing users to switch back and forth between Dart 1 and 2 versions of dartlang.org. The language selection menu looks like this:

> screen shot 2018-03-30 at 15 05 03

This PR adds the menu to master. A followup PR will add it to the 1.x branch.

### CODE REVIEW

**Comment by chalin** [comment]
@kwalrath - URL updated and staging server refreshed.

**Comment by chalin** [comment]
Any more feedback on this?

**Comment by kevmoo** [comment]
Wondering if the header should be hint that the site is in "preview" mode...or something.

The check mark is weird. So this is the "state" we're in – but also a link to the guide.

I think this is improvement, though...

**Comment by chalin** [comment]
> Wondering if the header should be hint that the site is in "preview" mode...or something.

It is my understanding that we won't officially be using the master branch version of the site until we switch dartlang.org over to Dart 2. At that point the menus will become:

- 1.24.3 (archive)
- 2.0.0 (stable)

> The check mark is weird. So this is the "state" we're in – but also a link to the guide.

Agreed about the weirdness of the link, but ... it is also my understanding that this menu is meant as a temporary measure, to be used for a few weeks? So this design is trying to be non-disruptive (e.g., not create new main nav entries).

I suppose that an alternative _might_ be to put the drop down under the "Dart". WDYT?

**Comment by kwalrath** [comment]
@chalin could you please mock up having the pulldown under the icon?

**Comment by chalin** [comment]
The logo links to the site landing page, so having a dropdown menu associated with the logo will suffer the same link weirdness issues.

As an alternative, I've prototyped having a _Version_ dropdown in the main nav bar:

> screen shot 2018-04-04 at 15 47 01

Staging server refreshed: https://dartlang-org-staging-0.firebaseapp.com

How does this fair against the previous prototype @kevmoo, et all?

Note:

- The _Version_ dropdown replaces the _Community_ link (we were running out of horizontal real estate).
- The _Version_ dropdown isn't visible on narrow displays.

**Comment by mit-mit** [comment]
With Dart 2 becoming default in Flutter beta 2, I think "preview" is understatement. Can we use "beta" instead?

**Comment by chalin** [comment]
Updated to use "beta". Staging server refreshed: https://dartlang-org-staging-0.firebaseapp.com

**Comment by chalin** [comment]
> But the toggle disappears after selecting 1.24.3.

Right, selecting 1.24.3 redirects you to the v1 site, which doesn't yet have a Version dropdown. Once this PR is approved and merged, a similar change will be made to the v1 site -- then readers will be able to navigate back and forth between the v1 and v2 sites.

**Comment by chalin** [comment]
The **main nav isn't visible on narrow displays**, so we'd lose the Version dropdown in those cases. I've added a Version menu to the sidenav. It looks like this when closed:

> screen shot 2018-04-05 at 09 22 01

After clicking the "dropdown" arrow, it looks like this:

> screen shot 2018-04-05 at 09 22 22

WDYT?

**Comment by chalin** [comment]
Btw, the sidenav is always accessible. If we'd like to make switching site versions less obvious, we could remove it from the main nav.

**Comment by chalin** [comment]
@kevmoo - the reason I prototyped the Version dropdown was because of the [link weirdness](https://github.com/dart-lang/site-www/pull/724#issuecomment-378374313) that you pointed out in the Language dropdown. It occurred to me that issue with the link could be fixed by adding an explicit link to the Language Overview page:

> screen shot 2018-04-05 at 10 35 14

This is also an opportunity to add a link to the Migration page too (as shown above). 
WDYT?

**Comment by kevmoo** [comment]
Would it be better to just have a top-level version dropdown?

**Comment by kevmoo** [comment]
Looking at https://v1-dartlang-org.firebaseapp.com/ – I like it!

Now just change the header "Version" to "Dart 2 (beta)"

**Comment by mit-mit** [comment]
I like it too. And I would simply not bother with adding a toggle option in narrow browsers. Hopefully a fairly small amount of developers will need this toggle.

**Comment by chalin** [comment]
Ok, thanks for the feedback.

@kevmoo - by changing "Version" to "Dart 2 (beta)" we'll have two "Dart" items in the main menu (the logo on the left being the other). Are you ok with that? Also, doesn't it seem strange to have a "Dart 2 (beta)" dropdown title with a menu entry "1.24.3 (stable)"?

**Comment by kevmoo** [comment]
I think that's fine.

**Comment by kwalrath** [comment]
@kevmoo, do you mean you were looking at https://dartlang-org-staging-0.firebaseapp.com/?

**Comment by chalin** [comment]
After a little fine tuning with @kevmoo and @kwalrath, we've agreed on a "Dart 2" dropdown (in the main nav only), with a Migration menu item. Please see the [staging server](https://dartlang-org-staging-0.firebaseapp.com/).

**Pull request merged**
