### PR TITLE
Migrate Async-Await Codelab to Null Safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
Continuing the work from the #2805 PR.

This PR adds the migrated version of the Async-Await Collections codelab in the `async-await_migrated.md`, following the migration guide.

This PR is split in different commits:

1. the original copy of the codelab and the examples folder.
2. contains the modification of the example code (no code was changed in the dart files, but the pubspec changed)
3. contains the modification of the codelab markdown and code.

I removed the references to the iframes hosted as gists, because I cannot update them and I assume they are not deprecated.

Live preview: https://mb-dart-dev-2.firebaseapp.com/codelabs/async-await_migrated

cc. @kwalrath @RedBrogdon

### CODE REVIEW

**Comment by kwalrath** [comment]
@miquelbeltran do you know why the build failed? (Should I review now or wait for you to fix it?)

**Comment by miquelbeltran** [comment]
Now it is fine, I missed two files necessary for running the tests.

**Review by kwalrath — APPROVED** [review]
LGTM!

**Comment by kwalrath** [comment]
We should probably remove the Dash puzzle piece... but it isn't hurting anything.

**Pull request merged**
