### PR TITLE
Document .pubignore

### PR DESCRIPTION
**Pull request by jonasfj**
Fixing https://github.com/dart-lang/site-www/issues/3399

Note: `.pubignore` support is set to ship in 2.14

### CODE REVIEW

**Comment by jonasfj** [comment]
Feel free to edit it... it's a little hard to explain concisely.

If we want to do better maybe we should make a separate page where we illustrate how it works using a few examples.

In short: we respect `.gitignore`, unless a folder contains a `.pubignore` then we allow the `.pubignore` to override the `.gitignore` files.

The hard part is the that it's not just the root folder that can contain a `.gitignore` or `.pubignore` file. And ignores from all parent folders under the package root-folder is applied to determine if a file/folder is ignored. For each parent folder we consider `.pubignore` (or `.gitignore` if the given folder doesn't contain a `.pubignore` file).

**Comment by parlough** [comment]
Do you think it would be worth adding a version note or some mention of when this was introduced, to avoid confusion by users who are not using 2.14+ yet?

**Comment by kwalrath** [comment]
I did a rewrite (of my words as much as Jonas's) and staged my version here:

https://kw-www-dartlang-1.web.app/tools/pub/publishing#what-files-are-published

We don't _usually_ publish docs before the stable release, so we might want to hold onto this for a while. Or not. At least there's a version note...

**Comment by kwalrath** [comment]
@jonasfj could you please make this a draft, so we don't accidentally push it early? Also, are my changes OK with you?

**Comment by kwalrath** [comment]
@jonasfj just checking again... are my changes OK by you?

**Comment by jonasfj** [comment]
> just checking again... are my changes OK by you?

@kwalrath LGTM!

**Review by kwalrath — APPROVED** [review]

**Pull request merged**
