### PR TITLE
updated dart tools to debugging.md

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@kwalrath 
can you please review this PR?
Thanks

**Review by woinbo — APPROVED** [review]
Changes look's great!

**Comment by Abhishek01039** [comment]
Thanks @woinbo

**Comment by Abhishek01039** [comment]
Hello @kwalrath 
can you please review this PR?
Thanks

**Comment by kwalrath** [comment]
Sorry, I had a really busy spell. Taking a look now...

**Review by kwalrath — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
