### PR TITLE
Correct fonts. Default images for gallery. Correct icons

### PR DESCRIPTION
**Pull request by FaisalAbid**

### CODE REVIEW

**Comment by FaisalAbid** [comment]
Just a quick update

**Comment by mit-mit** [comment]
Travis is not happy:

```
http://localhost:4000/
- (477:42) <img> => http://localhost:4000/assets/dash/2x/1-2%20target%20web@2x-80.jpg (HTTP 404)
- (486:42) <img> => http://localhost:4000/assets/dash/2x/1-3%20backend%20code@2x-80.jpg (HTTP 404)
- (495:46) <img> => http://localhost:4000/assets/dash/2x/1-1%20-%20aot%20compile@2x-80.jpg (HTTP 404)
Stats:
   17756 links
     196 destination URLs
     789 URLs ignored
       0 warnings
       3 errors
```

**Comment by FaisalAbid** [comment]
Ah, my mistake, fixing

**Comment by FaisalAbid** [comment]
staged as well. i'm loving how this is shaping up to be :)

**Pull request merged**
