### PR TITLE
fix syntax in lint excludes

### PR DESCRIPTION
**Pull request by pq**
/cc @kwalrath @sfshaza2 

fyi @danrubel

### CODE REVIEW

**Comment by kwalrath** [comment]
It sounds like this should be a warning, not a note, and we should make the warning harder to miss. How about something like this:

```
<aside class="alert alert-warning” markdown="1">
  If you disable any rules, then use key-value syntax to enable rules.
  For example, the preceding example can’t use `- await_only_futures`;
  instead, it must use `await_only_futures: true`.
  The reason it can’t use the dash shortcut (`-`) to enable `await_only_futures`
  is that YAML doesn't support mixing list and key-value syntaxes.
  </aside>
```

**Comment by pq** [comment]
Thanks @kwalrath.  Updates made!

**Comment by kwalrath** [comment]
Thanks, @pq!

**Comment by pq** [comment]
Cheers @kwalrath.  Thanks for the help word-smithing. 😄   Happy to do it.

Should I ignore the (unrelated) build breakage?

**Comment by kwalrath** [comment]
> Should I ignore the (unrelated) build breakage?

Yes, ignore it. I’m following up on that.

**Comment by kwalrath** [comment]
The build is fixed, woohoo!

**Pull request merged**
