### PR TITLE
Dart 2 stable

### LINKED ISSUE #866: Enabling Dart 2 type system: instructions unclear
Location: https://www.dartlang.org/guides/language/analysis-options#enabling-dart-2-semantics

The paragraph linked above explains how to enable Dart 2 semantics by adding adding `strong-mode: true`.

Then, the next paragraph states that one can **optionally** add flags to enable stricter checks than Dart's type system requires (and links to info about Dart 2's type system). But directly below the code block, states that these flags are **required** to enable the Dart 2 type system ~~(which is true in SDK 2.0.0-dev54.0)~~.

### PR DESCRIPTION
**Pull request by chalin**
Update:
- [x] Banner
- [x] Travis Dart version:
  - [x] Try stable/raw/2.0.0
  - [x] `stable`
- [x] Necessary doc updates (parts marked with `update-for-dart-2`)
  - [x] Dart 2 stable changes to site-shared pages https://github.com/dart-lang/site-shared/pull/27
  - [x] Drop [Enabling Dart 2 semantics (SDK <2.0.0-dev.68.0)](https://www.dartlang.org/guides/language/analysis-options#enabling-dart-2-semantics-sdk-200-dev680)?
  - [x] Fix a number of "Effective Dart" issues. #1050
    - [x] `whereType()` warning status -- see https://github.com/dart-lang/site-www/issues/995#issuecomment-410286160 - fixed by
  - [x] Dart 2 async note tweaks #1045
- [x] Example pubspecs: set min SDK to 2.0.0
- [x] "Hello DartPad" image SDK version

Fixes #866 (the problematic section is being dropped).

---

**Staged**, e.g., for the updated banner, see:

- Frontpage: https://sz-www-1.firebaseapp.com
- Any other page, such as the [Language Tour](https://sz-www-1.firebaseapp.com/guides/language/language-tour)

cc @Sfshaza

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @timsneath

**Comment by chalin** [comment]
I've committed the updated banner so that we can agree on the text. Other changes to the repo will be necessary. These will follow shortly.

**Comment by Sfshaza** [comment]
Thanks, Patrice!

**Comment by kevmoo** [comment]
Do we want to create a "GA" branch to merge all of these into? Then we can just hit the big button on Monday?

**Comment by chalin** [comment]
> Do we want to create a "GA" branch to merge all of these into? Then we can just hit the big button on Monday?

Sounds good. If it's ok with you, I'll use the branch for this PR.

**Comment by kevmoo** [comment]
Perfect!

**Comment by kevmoo** [comment]
Ah...uh...okay. So you're just going to pile more commits onto this branch?

**Comment by chalin** [comment]
Yes, that was my plan. (I can always change to the `dart2` branch if you find there are too many changes, but I don't think that'll happen. The site is very close to Dart-2.0-ready already :)

**Comment by chalin** [comment]
@kevmoo - can you please confirm that it is ok to keep [Enabling Dart 2 semantics (SDK <2.0.0-dev.68.0)](https://www.dartlang.org/guides/language/analysis-options#enabling-dart-2-semantics-sdk-200-dev680).

**Comment by kevmoo** [comment]
> can you please confirm that it is ok to keep Enabling Dart 2 semantics 

I'd bury that at the end of the page, if we keep it at all, @chalin – thoughts @Sfshaza ?

**Comment by chalin** [comment]
> I'd bury that at the end of the page, if we keep it at all

After second thought, I'd vote to remove it. Agreed @kevmoo?

**Comment by kevmoo** [comment]
Please!

**Comment by chalin** [comment]
@kevmoo - do we have a thumbs up for the banner?

**Pull request merged**
