### PR TITLE
Mark Windows 11 as supported

### PR DESCRIPTION
**Pull request by parlough**
Windows 11 is growing to almost 10% of the Windows market share according to some sites, and I'm assuming among developers it is even larger. 

Once testing is added on the SDK side, we should signify support here.

### CODE REVIEW

**Comment by parlough** [comment]
@athomas Is it okay to mark Windows 11 as officially supported here?

**Review by domesticmouse — APPROVED** [review]

**Comment by mit-mit** [comment]
@athomas do we do any testing on 11?

**Comment by athomas** [comment]
> @athomas do we do any testing on 11?

Not currently.

**Comment by domesticmouse** [comment]
I'm developing Flutter desktop apps on Win11. We should probably add it to the test pool.

**Review by sfshaza2 — COMMENTED** [review]
lgtm but I defer to @mit-mit.

**Comment by mit-mit** [comment]
I'd prefer not to add this until we get the testing added.

But at 10% of share we really should get that done. @athomas is that something we can do fairly soon?

**Review by mit-mit — APPROVED** [review]

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by parlough** [comment]
Thanks for the followup!

**Pull request merged**
