### PR TITLE
📝 Indicates `dart create` without nnbd before 2.13

### PR DESCRIPTION
**Pull request by AlexV525**
Currently `dart create` will create with a nnbd template, so it won't require further migrations.

### CODE REVIEW

**Comment by parlough** [comment]
Thanks for this, good catch! What do you think about instead focusing the documentation around new versions which already have null-safe templates and just need to use `dart create` without migrating. Then add an an extra `version-note` explaining the extra requirement to migrate before 2.13? As time progresses most new users reading this should be using the latest stable SDKs with no need to migrate and for users who aren't yet they'll still have the version note to refer to.

As an example, [`dart analyze`](https://dart.dev/tools/dart-analyze) has this:
image

Which was implemented like:

```markdown
{{site.alert.version-note}}
  Before Dart 2.13, `dart analyze` supported only directory arguments.
{{site.alert.end}}
```

**Comment by AlexV525** [comment]
That would be great too!

**Comment by AlexV525** [comment]
I've removed the `create` anchor completely, with the version note alert instead.

**Comment by AlexV525** [comment]
Should I add my name to AUTHORS too?

**Review by parlough — APPROVED** [review]
Thanks for this, looks good to me.

**Review by kwalrath — COMMENTED** [review]
Looks great!

(I forgot we even had an AUTHORS file. flutter/website has one, too, although it's been updated a little more recently. I'll look into either deleting these or marking them as no longer maintained and pointing to GitHub history.)

**Pull request merged**
