### PR TITLE
Fixes bad subscript error on macOS

### PR DESCRIPTION
**Pull request by atsansone**

### CODE REVIEW

**Comment by parlough** [comment]
Could you provide some more context on the error you're running into? I can't seem to reproduce it on my end.

Also what color issues did you see? Not super important, but I'd prefer to avoid duplicating the colors across this file and `utils.sh`.

**Comment by MaryaBelanger** [comment]
@parlough I've been getting the [checksum error](https://github.com/dart-lang/site-www#dart-sdk-and-node-ppa-checksum-values) for docker this morning. So after `make fetch-sums`

```
tool/fetch-dart-sdk-sums.sh \
        --version latest \
        --channel stable

Copy the following output and replace the existing code in the Dockerfile:

\e[0;33mamd64_stable)\e[0m \
tool/fetch-dart-sdk-sums.sh: line 47: [-1]: bad array subscript
make: *** [fetch-sums] Error 1
```

**Comment by parlough** [comment]
@MaryaBelanger Are you running this inside of `make run`?

**Comment by MaryaBelanger** [comment]
@parlough No, because `make run` isn't working, it tells me to run `make fetch-sums`
This is the full output from `make run`, and `make up` gives me identical output

```
docker compose run --rm site bash
[+] Running 0/1
 ⠿ site Warning                                                                                                    1.3s
[+] Building 12.0s (9/22)                                                                                               
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ruby:3-slim-bullseye@sha256:a6f940b1fca8a057561ac86f431539df2e  0.0s
 => [base 1/4] FROM docker.io/library/ruby:3-slim-bullseye@sha256:a6f940b1fca8a057561ac86f431539df2e77b954370fa17  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 401.15kB                                                                              0.1s
 => CACHED [base 2/4] RUN apt update && apt install -yq --no-install-recommends       build-essential       ca-ce  0.0s
 => CACHED [base 3/4] RUN echo "alias lla='ls -lAhG --color=auto'" >> ~/.bashrc                                    0.0s
 => CACHED [base 4/4] WORKDIR /root                                                                                0.0s
 => ERROR [dart 1/3] RUN set -eu;     case "$(dpkg --print-architecture)_stable" in       amd64_stable)           12.0s
------
 > [dart 1/3] RUN set -eu;     case "$(dpkg --print-architecture)_stable" in       amd64_stable)         DART_SHA256="f64fbc5b90c6817d6f3a25cf9cec4277343cf265df233600838050639c593889";         SDK_ARCH="x64";;       arm64_stable)         DART_SHA256="f8c6d7e1b0f090c536a64a6a130b065533efd83c290f4510f42325389a0c27a5";         SDK_ARCH="arm64";;       amd64_beta)         DART_SHA256="0cd028e661deded1b141348ebab1aa82814ee5a73ef226ff6c40ea225ff311a2";         SDK_ARCH="x64";;       arm64_beta)         DART_SHA256="6c9384814d1d516eec616f40d22df161e219eb15d730105a28bf260f3274b4ed";         SDK_ARCH="arm64";;       amd64_dev)         DART_SHA256="1d11accc2253df64b927c2b631b9921e253943d6b14e338afa3d7e8f84f98af4";         SDK_ARCH="x64";;       arm64_dev)         DART_SHA256="8545067be105012f6d0dbb4426b7a28da6928f6f0e3d69e391cfd16dc4dfffbc";         SDK_ARCH="arm64";;     esac;     SDK="dartsdk-linux-${SDK_ARCH}-release.zip";     BASEURL="https://storage.googleapis.com/dart-archive/channels";     URL="$BASEURL/stable/release/latest/sdk/$SDK";     curl -fsSLO "$URL";     echo "$DART_SHA256 *$SDK" | sha256sum --check --status --strict - || (        echo -e "\n\nDART CHECKSUM FAILED! Run 'make fetch-sums' for updated values.\n\n" &&         rm "$SDK" &&         exit 1     );     unzip "$SDK" > /dev/null && mv dart-sdk "/usr/lib/dart" && rm "$SDK";:
#0 11.94 -e 
#0 11.94 
#0 11.94 DART CHECKSUM FAILED! Run 'make fetch-sums' for updated values.
#0 11.94 
#0 11.94 
------
failed to solve: executor failed running [/bin/sh -c set -eu;     case "$(dpkg --print-architecture)_${DART_CHANNEL}" in       amd64_stable)         DART_SHA256="f64fbc5b90c6817d6f3a25cf9cec4277343cf265df233600838050639c593889";         SDK_ARCH="x64";;       arm64_stable)         DART_SHA256="f8c6d7e1b0f090c536a64a6a130b065533efd83c290f4510f42325389a0c27a5";         SDK_ARCH="arm64";;       amd64_beta)         DART_SHA256="0cd028e661deded1b141348ebab1aa82814ee5a73ef226ff6c40ea225ff311a2";         SDK_ARCH="x64";;       arm64_beta)         DART_SHA256="6c9384814d1d516eec616f40d22df161e219eb15d730105a28bf260f3274b4ed";         SDK_ARCH="arm64";;       amd64_dev)         DART_SHA256="1d11accc2253df64b927c2b631b9921e253943d6b14e338afa3d7e8f84f98af4";         SDK_ARCH="x64";;       arm64_dev)         DART_SHA256="8545067be105012f6d0dbb4426b7a28da6928f6f0e3d69e391cfd16dc4dfffbc";         SDK_ARCH="arm64";;     esac;     SDK="dartsdk-linux-${SDK_ARCH}-release.zip";     BASEURL="https://storage.googleapis.com/dart-archive/channels";     URL="$BASEURL/$DART_CHANNEL/release/$DART_VERSION/sdk/$SDK";     curl -fsSLO "$URL";     echo "$DART_SHA256 *$SDK" | sha256sum --check --status --strict - || (        echo -e "\n\nDART CHECKSUM FAILED! Run 'make fetch-sums' for updated values.\n\n" &&         rm "$SDK" &&         exit 1     );     unzip "$SDK" > /dev/null && mv dart-sdk "$DART_SDK" && rm "$SDK";]: exit code: 1
make: *** [run] Error 17

```

**Comment by parlough** [comment]
Makes sense, I appreciate the extra context!

**Comment by atsansone** [comment]
@parlough : I did test this script multiple times. It does generate the correct result.

```bash
tool/fetch-dart-sdk-sums.sh \
		--version latest \
		--channel stable

Copy the following output and replace
the existing code in the Dockerfile
inside the 'set eu' case statement:


amd64_stable \
 DART_SHA256="492c0e835203c4402e3d8291d12b53927f0300c8080aaf63a9113c204255a735"; \
 SDK_ARCH="x64";; \
arm64_stable \
 DART_SHA256="61dbb462b48aee4f3184b6ecdd356632f39165ae8570fe77a62900a6444f702c"; \
 SDK_ARCH="arm64";; \
amd64_beta \
 DART_SHA256="0cd028e661deded1b141348ebab1aa82814ee5a73ef226ff6c40ea225ff311a2"; \
 SDK_ARCH="x64";; \
arm64_beta \
 DART_SHA256="6c9384814d1d516eec616f40d22df161e219eb15d730105a28bf260f3274b4ed"; \
 SDK_ARCH="arm64";; \
amd64_dev \
 DART_SHA256="5fe7f37d6dc63bf8d3d0cd511a71c5b563d31376bc854e107be577925fd495a1"; \
 SDK_ARCH="x64";; \
arm64_dev \
 DART_SHA256="fa48e48f77c5673e64c160278ed5623d938cb075143203221f8006baa8388966"; \
 SDK_ARCH="arm64";; \

tool/fetch-node-ppa-sum.sh
NODE_SHA256=2a7d087bd1843b760f9c7462dfd687869655cebf42605fdaf8a746892cf4e9d6 node_ppa.sh; \
```

**Comment by parlough** [comment]
Yeah, the fix makes sense, thanks! I've opened https://github.com/dart-lang/site-www/pull/4446 which includes this and a few other minor fixes, while still using the color functionality from `utils.sh`.

**Comment by atsansone** [comment]
Superceded by #4446.

**Pull request closed without merging**
