### PR TITLE
A simple typo on null-safety page

### PR DESCRIPTION
**Pull request by JHBitencourt**
The word default is duplicated.

### CODE REVIEW

**Comment by parlough** [comment]
This one is quite funny. I actually think in this case it may have been intentional as `null` is the _default_ default value. 

Not saying this change is wrong, just enjoyed the sentence 😁

**Comment by JHBitencourt** [comment]
Well, if that's the case and intention, this can be ignored :D

**Comment by kwalrath** [comment]
Thanks for the PR @JHBitencourt, and for the interpretation @parlough! It does seem ambiguous. @munificent wrote this and gets to choose whether to change it. :D

**Comment by mit-mit** [comment]
I'm also of the impression that we mean "the _default_ default". Adding italics like that hopefully would make that clearer?

**Review by kwalrath — APPROVED** [review]

**Pull request merged**
