### PR TITLE
Delete /tools/dart-vm

### PR DESCRIPTION
**Pull request by kwalrath**
Contributes to #2719

Staged:

https://kw-staging-dartlang-2.web.app/tools/dart-vm

### CODE REVIEW

**Comment by kevmoo** [comment]
I'm okay with it, but it might be good to double check with @mit-mit – who is OOO until next week IIRC

**Review by parlough — APPROVED** [review]
This seems like a good idea to me. I thought calling this page "The Dart VM" (dart-vm) was a bit confusing as it only talked about the VM's ability to run programs.

**Comment by kwalrath** [comment]
I converted this to a draft so we wouldn't accidentally merge this change before @mit-mit gets a chance to see it.

**Review by mit-mit — APPROVED** [review]

**Pull request merged**
