### PR TITLE
Fixed double quotes, added override annotation

### PR DESCRIPTION
**Pull request by iLoveDocs**
- Replaced double string quote with single. 
- Added override annotation to make it easier to read that we're overriding a method from parent, because the heading itself talks about do this when overriding a method, (not sure if this should be done in docs but as guidelines suggest we should do that)
- Added `.` at the end of comment (according to Dart comment style). 

These are not the major changes in any way, but it is my first PR, so not sure how to do a pull request, I'll surely be able to make some significant changes in other pages of Dart once I realise how things work.

### CODE REVIEW

**Comment by kwalrath** [comment]
@munificent do these changes LGTY? I'll figure out what happened to the build.

**Comment by kwalrath** [comment]
Ah, the build break is just because the code was updated in the .md files but not the .dart files they auto-include from. E.g. the first snippet you changed was auto-included using the following, which means that the build will fail until we update `examples/strong/lib/strong_analysis.dart`:

```
<?code-excerpt "strong/lib/strong_analysis.dart (opening-example)" replace="/list(?=\))/[!$&!]/g"?>
```

Do you have (or want to learn) the git knowledge to update this PR with the relevant Dart files, or would you like me to add to this PR?

**Comment by kwalrath** [comment]
@domesticmouse can you take a look at the code?

**Comment by domesticmouse** [comment]
Code changes LGTM. I'll hold the proper approval until the changes are migrated to the relevent Dart files =)

**Comment by iLoveDocs** [comment]
@kwalrath
>Oops, I assumed these changes were to the null safety article, but they're to older docs.

I actually wanted to make the changes in the null safety page but that page was too long for my first edit. So, I decided to edit the current page.

>Ah, the build break is just because the code was updated in the .md files but not the .dart files they auto-include from.

I forgot to make the changes in the .dart file.

>Do you have (or want to learn) the git knowledge to update this PR with the relevant Dart files, or would you like me to add to this PR?

I have no knowledge of it, but would love to learn that. I have a confusion though. Let's see there are 5 code changes made by me in the .md file and those 5 code snippets belong to 5 different `.dart` files in the `example` folder, I am supposed to edit each of those files, right? And if yes, then how do I upload those files after editing to this PR page? Isn't it too much of work; editing files in 2 places with exact same changes? Maybe I am not doing it the right way.

**Comment by kwalrath** [comment]
If you have a local copy of the git repo, and you have the build working, then you only update the code in the .dart files, and then run a tool to update the .md file. But getting the build to work locally takes time, and some people never get it to work due to local configuration issues.

I'll be happy to make the changes locally and upload them to this PR.

**Comment by iLoveDocs** [comment]
>If you have a local copy of the git repo, and you have the build working, then you only update the code in the .dart files, and then run a tool to update the .md file. But getting the build to work locally takes time, and some people never get it to work due to local configuration issues.

I don't have a local copy, and I am sure I'd be one of those. 

>I'll be happy to make the changes locally and upload them to this PR.

How nice of you! 

And, does it mean that the next time I make some changes in any of the Dart documentation by editing .md file only, I'll eligible to create a corresponding PR and you guys can do the local build on your own? (I mean is it OK to leave that part for you people or am I supposed to update the .dart files anyhow?)

**Comment by kwalrath** [comment]
> And, does it mean that the next time I make some changes in any of the Dart documentation by editing .md file only, I'll eligible to create a corresponding PR and you guys can do the local build on your own? (I mean is it OK to leave that part for you people or am I supposed to update the .dart files anyhow?)

Yes, it's fine, at least for now. Getting good fixes in trumps inconvenience right now. I'm hoping that, over time, we'll make it easier to update code and/or we'll get help from more people who are comfortable building the site.

**Comment by kwalrath** [comment]
I'm starting on this now.

**Comment by kwalrath** [comment]
Woot! Tests are passing! (The beta build broke, but I'll try fixing that separately.)

**Comment by iLoveDocs** [comment]
@Kathy

Quoting [this page](
https://dart.dev/guides/language/sound-problems#static-errors-and-warnings)

The first solution (explicit type declaration) won't work after NNBD
arrival, so shall we remove this solution altogether from docs or wait for
NNBD to come in the stable version?

**Comment by kwalrath** [comment]
@iLoveDocs We should add a comment about the first solution not working under null safety. (See https://github.com/dart-lang/site-www/pull/2621#issuecomment-688995793 for a proposal.)

**Pull request merged**
