### PR TITLE
Dart VM -> Server

### LINKED ISSUE #965: Dart VM -> Server
From https://github.com/dart-lang/site-www/issues/245#issuecomment-399995210.

- [x] [Get Started page](https://www.dartlang.org/guides/get-started)
- [x] Install page - #964
- [x] [Platforms page](https://www.dartlang.org/guides/platforms)
- [x] Sidenav - all pages (when viewed from wide displays) other than the front page. #970
- [x] https://www.dartlang.org/guides/json
- [ ] Changing `/dart-vm` URLs to be `/server` (with appropriate redirects)

### PR DESCRIPTION
**Pull request by artem-galas**
Fixed #965 

WIP

I changed folders, images path, and step path.
But there are some **issue** which, I suppose, related to redirection on `firebase.json`
If you try go to `/server` it redirects you to `https://dart-lang.github.io/server/` I'm not sure how to fix this this. I've removed `181` line on `firebase.json` but it didn't help :(

I also consider to move article `https://dart-lang.github.io/server/codelab/` into `dart-www` codelab and update it as well to Dart 2. 
But it would be great to move **all** content from to `https://dart-lang.github.io/server` `dart-www` site.

What do you think about it?

### CODE REVIEW

**Comment by kwalrath** [comment]
I was able to remove the redirect to https://dart-lang.github.io/server (it involved removing that line, doing a jekyll build, reserving, and then opening a URL in an incognito browser). But we'd need to not only update our old redirects, but to add a redirect for every single link that's currently under */dart-vm/* or was handled by line 181, which would be quite a few. @chalin, do you know any alternative?

**Comment by chalin** [comment]
Yes, you can add a rule with a named `:foo*` (catch-all) pattern. E.g., https://github.com/dart-lang/site-www/blob/67b66aeb79ba5d57e77618e5bc830fa30e02322e/firebase.json#L133

```
{ "source": "/effective-dart/:page*", "destination": "/guides/language/effective-dart/:page*", "type": 301 },
```

**Comment by chalin** [comment]
@artem-galas - thanks for the PR. As you might have noticed, the [build is failing](https://travis-ci.org/dart-lang/site-www/jobs/470687850) due to 404s:

```nocode
http://localhost:4000/articles
- (213:6) 'Articles..' => http://localhost:4000/articles/dart-vm (HTTP 404)
http://localhost:4000/articles/language
- (224:6) 'Server-s..' => http://localhost:4000/articles/dart-vm (HTTP 404)
http://localhost:4000/articles/libraries
- (239:6) 'Server-s..' => http://localhost:4000/articles/dart-vm (HTTP 404)
http://localhost:4000/dart-vm/io-library-tour
- (479:0) 'server-s..' => http://localhost:4000/dart-vm (HTTP 404)
http://localhost:4000/guides/testing
- (220:4) 'server-s..' => http://localhost:4000/dart-vm (HTTP 404)
http://localhost:4000/tools
- (237:10) 'Tools fo..' => http://localhost:4000/dart-vm/tools (HTTP 404)
http://localhost:4000/tools/build_runner
- (245:0) 'reflection' => http://localhost:4000/articles/dart-vm/reflection-with-mirrors (HTTP 404)
- (245:0) 'reflection' => http://localhost:4000/articles/dart-vm/reflection-with-mirrors (HTTP 404)
http://localhost:4000/tools/sdk
- (440:10) 'dart' => http://localhost:4000/dart-vm (HTTP 404)
```

These should be fixed, independently of the redirect rules that might be added. Thanks!

**Comment by artem-galas** [comment]
I've updated the all necessary links, and also put 
redirects in `firebase.json`-
`{ "source": "/dart-vm/:page*", "destination": "/server/:page*", "type": 301 },`

But one think was left - `site-shared/index.md` has link to `dart-vm` but it should works, according to redirects

**Comment by kwalrath** [comment]
We're getting close! I just ran `pub run linkcheck -i deploy/urls/old_site_urls.txt` (per #1068), and I found 14 old URLs that no longer work. Four links were broken before (see below), but I don't care because nobody seems to look for them.

Ten 404s are new, and these *do* matter:

http://localhost:4000/articles/benchmarking/ (HTTP 301 => 404)
http://localhost:4000/articles/native-extensions-for-standalone-dart-vm/ (HTTP 301 => 404)
http://localhost:4000/articles/numeric-computation/ (HTTP 301 => 404)
http://localhost:4000/articles/reflection-with-mirrors/ (HTTP 301 => 404)
http://localhost:4000/articles/simd/ (HTTP 301 => 404)
http://localhost:4000/docs/tutorials/cmdline/ (HTTP 301 => 404)
http://localhost:4000/docs/tutorials/get-started/ (HTTP 301 => 404)
http://localhost:4000/docs/tutorials/httpserver/ (HTTP 301 => 404)
http://localhost:4000/performance/ (HTTP 301 => 404)
http://localhost:4000/faq
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)

http://localhost:4000/faq#q-why-didnt-google-build-a-bytecode-vm-targetable-by-multiple-languages-including-dart
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)

http://localhost:4000/faq#types
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)
- (322:4) 'mirrors ..' => http://localhost:4000/articles/libraries/reflection-with-mirrors (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4000/articles/libraries/reflection-with-mirrors (301)
    - /articles/dart-vm/reflection-with-mirrors (404)

For the record, here are the four additional 404s:

http://localhost:4000/slides/ (HTTP 301 => 404)
http://localhost:4000/slides/2011/12/gtug/ (HTTP 301 => 404)
http://localhost:4000/slides/2012/06/io12/dart-a-modern-web-language.html (HTTP 301 => 404)
http://localhost:4000/slides/2012/06/io12/putting-the-app-back-into-web-apps.html (HTTP 301 => 404)

**Comment by artem-galas** [comment]
@kwalrath Thanks!
I've updated the brunch there only 4 previous wrong link are left (slides I mean).

**Comment by dcharkes** [comment]
Some of the urls are still cached by search. For example first result https://www.google.com/search?q=dart+native+extensions. Shouldn't these relocated pages be 301's?

**Comment by chalin** [comment]
Thanks for pointing that out @dcharkes, some redirect rules are missing. I'll track this via #1281.

**Pull request merged**
