### PR TITLE
Reorder constructors in ‘Effective Dart: Usage’ and ’Constructors’ examples

### PR DESCRIPTION
**Pull request by Turskyi**
In this commit, I have reordered the constructors in all examples on the ‘Effective Dart: Usage’ (https://dart.dev/effective-dart/usage) and ‘Constructors‘ (https://dart.dev/language/constructors) pages to align with the Dart and Flutter style guides.  

Specifically, I followed the guidelines from ‘sort_constructors_first’ (https://dart.dev/tools/linter-rules/sort_constructors_first), ‘sort_unnamed_constructors_first’ (https://dart.dev/tools/linter-rules/sort_unnamed_constructors_first), ‘Constructors come first in a class’ (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#constructors-come-first-in-a-class) and ‘Order other class members in a way that makes sense‘ (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#order-other-class-members-in-a-way-that-makes-sense).  

By placing constructors before other class members, these examples now adhere to the recommended style and provide clearer, more consistent code for Dart and Flutter developers.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn’t contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Review by parlough — COMMENTED** [review]
Hi @Turskyi, thanks for opening the pull request!

This is a bit challenging as this is one situation in which Dart traditionally has a different style than Flutter, where Dart developers often place fields (instance variables) before constructors.

This results in some clarity about the properties of a class but more importantly is likely more familiar to users of other related programming languages.

If you think there is discussion worth having on changing this standard though, I'd consider opening an issue on this repo with your thoughts so feedback can be collected.

Thanks again and sorry it's not so clear cut! Let me know what you think :)

**Comment by Turskyi** [comment]
Hello @parlough, thank you for your thoughtful response to my pull request!

I appreciate your perspective on the tradition of placing fields before constructors in Dart. It’s interesting to learn about these nuances and how they can vary between Dart and Flutter.

I understand that this tradition might be more familiar to developers from other programming languages. However, as Dart is often used in conjunction with Flutter, I believe it’s important to consider the impact of these stylistic differences on the developer experience.

Switching between different styles when working on Dart and Flutter projects could potentially lead to confusion. Therefore, I proposed aligning the examples in the Dart documentation with the official Dart and Flutter style guides, specifically the ‘sort_constructors_first’ rule.

I’m curious to learn more about the origins of this tradition and its continued support, especially given the existence of the official Dart linter rule (https://dart.dev/tools/linter-rules/sort_constructors_first) that recommends placing constructors first. Is there a specific reason why this tradition is favoured over the official linter rule in the Dart community?

Regarding your comment about the placement of fields providing clarity about the properties of a class, I’d like to share an example from Java:
```Java
public class Book {
    private String title;

    public Book(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
```
In this Java class, the getter and setter methods for the ‘title’ field are placed after the constructor. A similar structure can be seen in Dart:
```Dart
class Book {
  Book(this.title);

  String title;
}
```
In this Dart class, ‘title’ is essentially a getter and is placed after the constructor. This structure aligns with the style seen in other programming languages and could potentially make the code more intuitive for developers.

I noticed that there have been discussions and issues opened regarding the ordering of class members in Dart:
1. "Improved ordering support for class members" https://github.com/Dart-Code/Dart-Code/issues/4657
2. "Enforce consistent order of class members" https://github.com/dart-lang/linter/issues/2367

These discussions highlight the importance of consistency in code structure. In my opinion, maintaining a consistent order, even if it’s not perfect, could be more beneficial than having multiple good “traditions” within the same code base.

If you believe that further discussion is needed, I’m open to creating another issue to continue this conversation.

Thank you again for your time and consideration. 😊

**Comment by atsansone** [comment]
This work was duplicated in #5718

**Comment by atsansone** [comment]
Closing this issue as Won't fix.

**Comment by Turskyi** [comment]
Hello @atsansone,

I noticed that the pull request I submitted was closed with the status "Won't fix." I understand that not all contributions may align with the project's direction or current priorities, but I was hoping to get some feedback on the decision to close the request.

Could you please provide some insight into the reasons behind this decision? Understanding the rationale would be greatly beneficial for my future contributions and for ensuring they are in line with the project's goals.

Thank you for your time and consideration.

**Pull request closed without merging**
