### PR TITLE
[site-www] Adding the code files for the codelabs cheatsheet according to src

### LINKED ISSUE #2295: Add and auto-include cheatsheet code samples
We need to add the cheatsheet code samples in the repo so that we can link the code-excerpts in the source file.

Context: #1803 

cc: @kwalrath

### PR DESCRIPTION
**Pull request by jddeep**
[site-www] Adding the code files for the codelabs cheatsheet according to src

Fixes #2295

### CODE REVIEW

**Comment by kwalrath** [comment]
It looks like we might need to add some ignore comments for `unused_local_variable` and to fix bin/null_aware_operators.dart:

```
Analyzing analysis_options.yaml, bin, lib, test...
  lint â€¢ Avoid using `null` in `if null` operators. â€¢ bin/null_aware_operators.dart:10:9 â€¢ unnecessary_null_in_if_null_operators
  hint â€¢ The value of the local variable 'aListOfStrings' isn't used. â€¢ bin/collection_literals.dart:2:9 â€¢ unused_local_variable
  hint â€¢ The value of the local variable 'aSetOfStrings' isn't used. â€¢ bin/collection_literals.dart:3:9 â€¢ unused_local_variable
  hint â€¢ The value of the local variable 'aMapOfStringsToInts' isn't used. â€¢ bin/collection_literals.dart:4:9 â€¢ unused_local_variable
  hint â€¢ The value of the local variable 'aListOfInts' isn't used. â€¢ bin/collection_literals.dart:10:9 â€¢ unused_local_variable
  hint â€¢ The value of the local variable 'aSetOfInts' isn't used. â€¢ bin/collection_literals.dart:11:9 â€¢ unused_local_variable
  hint â€¢ The value of the local variable 'aMapOfIntToDouble' isn't used. â€¢ bin/collection_literals.dart:12:9 â€¢ unused_local_variable
1 lint and 6 hints found.
No analysis errors or warnings should be present in original source files.
Ensure that these issues are disabled using appropriate markers like: 
  // ignore_for_file: stable, some_analyzer_error_or_warning_id
```

**Comment by jddeep** [comment]
Added all the needed files.
@kwalrath Can you help me in adding the ignore comments for these lints and warning as shown by travis :) Thanks.

**Comment by kwalrath** [comment]
> Added all the needed files.
> @kwalrath Can you help me in adding the ignore comments for these lints and warning as shown by travis :) Thanks.

Sure thing, I'll take a look now. Thanks for all the work you've done already!

**Comment by kwalrath** [comment]
The build is passing, woohoo! Some of these ignores might not be necessary in 2.8... or at least, the build was passing locally for me after I made my second commit.

**Comment by kwalrath** [comment]
We'll need some changes to these (e.g. doc regions) once we auto-include the excerpts, but this is a good first pass to make sure that the snippets are good as-is.

**Comment by kwalrath** [comment]
Thank you, @jddeep! Are you up for creating a PR that auto-includes these excerpts?

**Pull request merged**
