### PR TITLE
removed deprecated pub publish

### PR DESCRIPTION
**Pull request by Abhishek01039**
I have changed `dart` in the place of `pub` in src/tools/pub/publishing.md as mention in https://github.com/dart-lang/site-www/issues/2617 issue.

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@kwalrath 
can you please review this PR?
Thanks

**Comment by kwalrath** [comment]
Sorry for the review delay, @Abhishek01039; I was out for the winter holidays.

Did you test these commands? I thought the command would be `dart pub publish`, not `dart publish`.

**Comment by Abhishek01039** [comment]
Oh my bad! @kwalrath 
can you please review it again?
Thanks

**Review by kwalrath — APPROVED** [review]
LGTM. Thanks, @Abhishek01039!

**Pull request merged**
