### PR TITLE
Break up the Language Tour

### PR DESCRIPTION
**Pull request by MaryaBelanger**
Staged: https://dart-dev--pr4612-language-tour-2-koullabo.web.app/

---

_Waiting for #4604 to merge first -- Fixes #4588_

---

This PR breaks sections of the language tour into separate pages and lists them directly under "Language" in the side nav, so the features of the Dart language are visible and navigable more easily than the previous single page. 

_(see #4588 and #4565 for background; see [Kotlin](https://kotlinlang.org/docs/basic-types.html) and [Swift](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/) docs for inspiration/direction)_

## What this PR _is_:

- **Addressing the side nav and new organization.** Please comment and review the new layout of the side nav under "Language".
  
  image

- **Addressing the grouping of info on the new pages.** Please let me know if the new page groupings make sense. They almost entirely follow the structure of original Language Tour -- I didn't write that, I won't be improving that structure in this PR beyond what's necessary.
- Fixing links to the old language tour page. 
- Adding manual redirect links to old language tour page

### TODO: 
In this PR...
- [x] Manually add links to old language tour page, in case external links end up there
  - Link on every section to its new page/location  
- [x] Search the entire site source for internal links to `/language-tour`/`#<section>` to change to new page/location
- [x] Add ignore thing from language-tour for code excerpts
- [ ] Figure out "<< Previous" / "Next >>" buttons for bottom of each page
  - Parkers going to write a script after this lands
- [x] Prevent old `/language-tour` page from showing up in search results 
- [ ] Add a little introduction about the language tour to intro page
- [ ] Firebase redirects after this PR

---

## What this PR _is not_:

This PR is not...
- **Addressing content.** 
  - Please do not review the contents of any of the new pages, I didn't write it. Open a separate issue for... 
    - redundancy
    - sub-optimal information flow _within a page_ (page-to-page is in scope for the PR)
    - inaccurate/outdated content
    - etc.
- **Major rewrite.** 
  - Splitting up or rearranging certain content requires major rewrites or at minimum analysis of the existing content; that will not happen as part of this PR.
  - Referring to the [Type System](https://dart.dev/guides/language/type-system) page and all the [Null Safety content](https://dart.dev/null-safety), which can and should be split up into more granular topic by page, but it's not straight forward (see TODO below)
- **Creating a "Getting started"** or de facto intro page.
  - Again, I will not be doing any major rewrites in this PR, and consolidating [Language samples](https://dart.dev/samples) and [Language cheatsheet](https://dart.dev/codelabs/dart-cheatsheet) intro content is a major rewrite. 

### TODO: 
In future PRs...
- [ ] Break up the topics on the [Type System](https://dart.dev/guides/language/type-system) page to more granular topics:
  - Type inference
  - Type promotion
  - etc.
- [ ] Re-work the contents under [Null Safety](https://dart.dev/null-safety) to more granular topics (see this [comment](https://github.com/dart-lang/site-www/issues/4588#issuecomment-1438781068)) _and_ minimize reference to unsound null safety (see #4584 )
  - Introduce "nullable types" page under "Types"
  - Add "null" content to "Variables"
  - Put the rest of the null safety content somewhere else/delete it (migrating, unsound, faq. etc)
  - Break existing content up into these sections:
    - Non-null vs nullable
    - Correctness
    - Flow analysis
    - Working with nullable topes
    - ~Core library changes~
- [ ] Consolidate the future/async/await content on the Concurrency page, into the new `/language/async` page.
  - Info is redundant, Concurrency page should just be about Isolates

### CODE REVIEW

**Comment by parlough** [comment]
See https://github.com/dart-lang/site-www/issues/4610#issuecomment-1440751499 for my thoughts on libraries and visibility.

**Comment by MaryaBelanger** [comment]
@parlough where do you think the library content should go? Does it make sense as an entry under "variables & expressions"? (not knowing where to put it definitely influenced my impulse to move it under libraries 🙃 )

**Comment by parlough** [comment]
I don't think it makes sense under Variables and expressions.

Perhaps a first-level doc called **Libraries and imports** before **Classes and objects**. I don't believe imports are used much or at all before then.

**Review by atsansone — APPROVED** [review]
As discussed, I would move control flow and error handling up, but otherwise LGTM! 

GREAT JOB!

**Comment by mit-mit** [comment]
Looks great overall! A few comments:

1. I think we should move the Keywords page to the end of the Language < submenu, It's mostly a background page, and not something I think we should lead with
2. The Types > Type system page does indeed seem a bit odd in the new structure. Until the re-work PR for that, I think we should either move it up as the first page under Types >, or alternatively make it the last page there.

**Comment by mit-mit** [comment]
> I don't think Variables and expressions is the right place.

@parlough can you elaborate a bit on that? I was actually thinking that might be a good place (I'd just call the page `Libraries` and make it the last node under Variables and Expressions...

**Comment by parlough** [comment]
Libraries aren't really about variables or expression, it is a more high-level concept core to a lot Dart, nor is `import` an expression. 

Overall, the current **Variables and expressions** section doesn't make a lot of sense to me. If I'm looking to learn about **Libraries**, **Metadata**, or **Comments**, I would not think to expand **Variables and expressions**. None of them are about variables or expressions. Perhaps the problem is in the name of the section?

**Review by munificent — APPROVED** [review]

**Comment by MaryaBelanger** [comment]
I took everyone's comments into consideration and came up with the following structure as a compromise for the time being, as I need to merge this so I can start placing new Dart 3 pages in the new structure:

> **Language**
> - Introduction
> - **Syntax basics** _(I went with this title instead of "Variables and expressions", kind of like [this Kotlin section](https://kotlinlang.org/docs/basic-syntax.html). Probably still not ideal but I think it's vague enough to be a benign place holder)_
>   - Variables
>   - Operators
>   - Comments
>   - Metadata
>   - **Libraries & imports** _("Libraries & visibility" is back, changed to "imports". Also moved it with the other `/language` files and updated links across the site)_
>   - **Keywords** _(Moved "Keywords" to the end of the section)_
> - Types
>   - Built-in types
>   - Collection types
>   - Typedefs
>   - Generics
>   - **Type system** _(Moved "Type system" to the end of the section)_
> - Functions
> - **Control flow**  _(Moved "Control flow" up)_
> - **Error handling** _(Moved "Error handling" up)_
> - Classes & objects
>   - Classes
>   - Constructors
>   - Methods
>   - Extend a class
>   - Extension methods
>   - Enum types
>   - Mixins
>   - Callable classes
> - Concurrency
>   - Asynchronous support
>   - Isolates
> - **Null safety**  _(Moved "Null safety" to the end for now)_
>   - Sound null safety
>   - Migrating to null safety
>   - Understanding null safety
>   - Unsound null safety
>   - FAQ

Please open a new issue if anything isn't sitting right. Especially if it's really egregious, I'll try to fix it ASAP. Thanks all!

**Pull request merged**
