### PR TITLE
Make DartPad resizable in Tutorial > Server > Get started

### PR DESCRIPTION
**Pull request by chalin**
Adjustments to the DartPad in Tutorial > Server > Get started.

- Sets a min-height
- Make DartPad resizable -- addresses resize request from this thread: https://github.com/dart-lang/site-www/pull/2092/files#r346460620
   Screen Shot 2019-11-14 at 15 23 24

Staged at https://dart-dev-staging-1.firebaseapp.com/tutorials/server/get-started

@kwalrath @johnpryan : do you still want the min-height to be 200px or more?

Followup to #2092

### CODE REVIEW

**Comment by chalin** [comment]
cc @RedBrogdon

**Comment by kwalrath** [comment]
I don't have a strong opinion on 150 vs. 200 px height.

**Comment by chalin** [comment]
Ok, then I'd vote for keeping the frame short, since it can be resized. @johnpryan WDYT?

@kwalrath - other than than, are you liking the resizable frame feature?

**Comment by chalin** [comment]
@johnpryan - I'll submit a followup PR if you think something needs adjustment. Travis is green, and Kathy approved, so I'll merge now.

**Pull request merged**
