### PR TITLE
Fix code example for "Using generic methods"

### PR DESCRIPTION
**Pull request by ben4ever**
This fixes the following:
1. The proper syntax for the assign-if-null operator is `??=` instead of `?=`.
2. `??=` cannot be used in combination with declaring a variable (i.e. within the same statement). The reason for this might be because the variable is always `null` at the point of declaration anyway.

### CODE REVIEW

**Comment by kwalrath** [comment]
Is there a discussion of this change somewhere? I'd like to know more about it.

**Comment by ben4ever** [comment]
Sorry, I didn't provide any information in my first comment. I just updated the comment now.

**Comment by kwalrath** [comment]
Looking at the [dartpad](https://dartpad.dartlang.org/a02c53b001977efa4d803109900f21bb) referred to just above the sample code, it should indeed be `=` instead of `?=`.

Good catch! Would you mind changing the PR?

**Comment by ben4ever** [comment]
Ah right, didn't even notice that link to the dartpad example.

I simply changed the `?=` to `=` now. Or did you want me to include the
```dart
  if (!(ts?.length > 0)) {
    // ts is null or empty
    return null;
  }
```
part as well for a more extensive example?

**Comment by kwalrath** [comment]
How you have it now is good. Thanks very much!

**Pull request merged**
