### PR TITLE
Fix TODOs for SCSS

### PR DESCRIPTION
**Pull request by atsansone**
Fixes https://github.com/dart-lang/site-www/issues/2859

### CODE REVIEW

**Comment by atsansone** [comment]
@parlough : This change does affect the display of `h2` because it inherits the styles from `shared` for Flutter. I'm willing to go with that for now to get this cleared.

**Comment by parlough** [comment]
I'll take a look at this early next week.

However, after taking a look at the staged site, the new h2 size is very large for the Dart site compared to other content around it and the other headers. I'd rather address that before landing this since there is no rush on these changes.

**Comment by atsansone** [comment]
@parlough : You're right. I noted why in earlier comments. We may want to consider fixing this across both sites.

**Review by parlough — APPROVED** [review]
Thanks!

I pushed a few more fixes, including reverting h2 to the old size, adjusting some values, moving some variables, and removing some old comments.

**Pull request merged**
