### PR TITLE
Update faq.md

### LINKED ISSUE #2799: 'Null safety: frequently asked questions' page issue
Page URL: https://dart.dev/null-safety/faq.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/faq.md

Description of issue:
I was just wondering about the following point:

> ## How do I signal that the return value from a Map is non-nullable?
> 
> The
> [lookup operator](https://api.dart.dev/stable/dart-core/Map/operator_get.html)
> on Map (`[]`) by default returns a nullable type. There's no way to signal to
> the language that the value is guaranteed to be there.
> 
> In this case, you should use the bang operator (`!`) to cast the value back to
> V:
> 
> ```dart
> if (blockTypes.containsKey(key)) {
>   return blockTypes[key]!; // blockTypes[key] is non-nullable
> } else {
>   throw ArgumentError('Could not read block type.');
> }
> ```

From my point of understanding this should be changed to something like this:

> ## How do I signal that the return value from a Map is non-nullable?
> Do not try to do that. Simply test whether the return value is null or not.
> 
> ```dart
> final blockType = blockTypes[key]
> if (blocktype != null) {
>   return blocktype;
> } else {
>   throw ArgumentError('Could not read block type.');
> }
> ```

The argument being, that in multithreaded code the code snippet as present in the FAQ now could actually fail with a null pointer exception, due to the value at key being possibly removed between the `containsKey()` check and the actual use of the lookup operator `[]`.

### PR DESCRIPTION
**Pull request by SebastianJL**
Changes according to discussion in #2799.
Closes #2799.

### CODE REVIEW

**Comment by SebastianJL** [comment]
@googlebot I signed it!

**Comment by davidmorgan** [comment]
Looks good, thanks! Added Ryan for review as I don't have permission to merge here.

**Comment by ryanmcginnis** [comment]
thanks! over to Kathy (i don't have permission either). i've started the changes for the internal document.

**Review by kwalrath — APPROVED** [review]

**Comment by kwalrath** [comment]
LGTM! (And I'll get @ryanmcginnis commit permission.)

**Pull request merged**
