### PR TITLE
Show M1 SDKs in stable

### PR DESCRIPTION
**Pull request by mit-mit**
_Note by parlough: Wait until 2.14.0 is released to stable before merging._ 

_Note by mit: Turns out we need 2.14.1. Earlier builds did not have properly trained snapshots in `/bin`, so their startup time was very slow._ 

Fixes https://github.com/dart-lang/sdk/issues/47145

### CODE REVIEW

**Review by kwalrath — APPROVED** [review]

**Review by athomas — APPROVED** [review]

**Comment by mit-mit** [comment]
@athomas updated this logic as per offline discussion, still LGTM?

**Comment by mit-mit** [comment]
Test failure also happens in master: https://github.com/dart-lang/site-www/actions/runs/1201957076

**Review by parlough — APPROVED** [review]
This change looks good to me. If you need the build to pass you'll need to merge in the `master` branch or rebase on top of it.

**Review by athomas — APPROVED** [review]

**Comment by parlough** [comment]
@mit-mit Should this be held off until a 2.14.1 build is available?

**Comment by mit-mit** [comment]
That build should be there shortly

**Comment by mit-mit** [comment]
Build is there, and new archive page confirmed working. Merging.

**Pull request merged**
