### PR TITLE
doc(mixins): Add override annotation on some code examples

### PR DESCRIPTION
**Pull request by tilucasoli**
include some override annotations for code examples that are not explicitly assigned.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn't contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn't use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/packages/excerpter) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Comment by MaryaBelanger** [comment]
Thanks for this @tilucasoli! I'm going to push a commit that adds a small note saying that the overrides are implicit, so they _can_ be omitted, but otherwise I agree that stating them explicitly is better for docs

**Comment by tilucasoli** [comment]
Thank you for your response! Where will you add this note? Would it be added for each page?

**Comment by MaryaBelanger** [comment]
I think probably around line 71, at the end of `## Specify members a mixin can call on itself` but before `### Define abstract members in the mixin`. That way we can say it applies to all the examples in the section.

**Review by MaryaBelanger — APPROVED** [review]
Decided against the note, so this is good to go! Thanks again @tilucasoli

**Pull request merged**
