### PR TITLE
Add missing ‘to’ in usage.md

### PR DESCRIPTION
**Pull request by smolck**

### CODE REVIEW

**Comment by smolck** [comment]
@googlebot I signed it!

**Comment by kwalrath** [comment]
@smolck, did you use the same email address to sign the CLA as is associated with your GitHub account?

**Comment by smolck** [comment]
> @smolck, did you use the same email address to sign the CLA as is associated with your GitHub account?

@kwalrath Yes, I did. I just updated it with my username, so I presume I just @ googlebot again and see if that works?

> LGTM. Thanks, @smolck!

No problem!

**Comment by smolck** [comment]
@googlebot I signed it!

**Pull request merged**
