### PR TITLE
Unmask Windows ARM64 beta channel downloads.

### PR DESCRIPTION
**Pull request by rmacnak-google**

### CODE REVIEW

**Review by parlough — APPROVED** [review]
Thank you! It's exciting to see this progress. Does this mean tests are now running on physical Windows ARM64 machines?

Don't mind the build failure. I'll get that fixed in a separate PR. Feel free to merge when you are ready.

**Comment by rmacnak-google** [comment]
Yes, we now have testing on physical Windows ARM64 devices provided by Flutter.

**Comment by rmacnak-google** [comment]
I don't have merge permissions.

**Comment by sortie** [comment]
Who is deploying this repository to production in practice? Do you need help deploying, I think I did it previously?

**Comment by parlough** [comment]
> Who is deploying this repository to production in practice? Do you need help deploying, I think I did it previously?

We deploy it on each commit to Firebase hosting currently with GitHub Actions: https://github.com/dart-lang/site-www/blob/e906315f66628d61ad6e9335c77205e79ca03fd9/.github/workflows/build.yml#L53. This works pretty well outside of someone needing to update the service account key every few months(?) to fix it. 

The changes should be live now at https://dart.dev/get-dart/archive#beta-channel :)

**Comment by sortie** [comment]
Oh that's perfect & easy

**Pull request merged**
