### PR TITLE
fix: language-tour.md spelling mistake

### PR DESCRIPTION
**Pull request by JJJYY**
# fix language-tour.md spelling mistake
`hexidecimal` => `hexadecimal`

### CODE REVIEW

**Comment by JJJYY** [comment]
I signed it!

**Comment by chalin** [comment]
@JJJYY - thanks for the fix. Was there a reason why you closed the PR before it was merged?

**Comment by JJJYY** [comment]
I google `hexidecimal ` and I find use `hexidecimal` in many place，and I am not confident my english, so I think I am error.

**Comment by chalin** [comment]
Your PR has the correct spelling. Thanks again for spotting that.

**Pull request merged**
