### PR TITLE
Tweak the iterables codelab

### PR DESCRIPTION
**Pull request by kwalrath**
Made the following changes:
* Don't include code that's already in the exercise.
* Tweak the words that refer to that code.
* Fix line breaks. (https://github.com/dart-lang/site-shared/wiki/Writing-for-Dart-and-Flutter-websites#semantic-line-breaks)
* Update descriptions in the list of codelabs.

I've also edited one of the samples (gists) to add "Lasagne". :) I didn't make all of them have that, though, because it would've required more changes than I was willing to make right now.

Staged:
https://kw-www-dartlang-1.firebaseapp.com/codelabs/iterables
https://kw-www-dartlang-1.firebaseapp.com/codelabs

### CODE REVIEW

**Comment by kwalrath** [comment]
@legalcodes it'd probably be easiest to look at the first and last commits separately. (The second one is almost all just line break rearrangement, although I might have sneaked in a minor wording change or two.)

**Comment by legalcodes** [comment]
Hmm, the solution for https://kw-www-dartlang-1.firebaseapp.com/codelabs/iterables still doesn't work, as the `User` class isn't included in the solution code.

**Comment by legalcodes** [comment]
Ditto for https://kw-www-dartlang-1.firebaseapp.com/codelabs/iterables#exercise-mapping-to-a-different-type

**Comment by kwalrath** [comment]
I'll fix those gists. Thanks for the review, @legalcodes!

**Pull request merged**
