### PR TITLE
Run Dart 2.3.2 dartfmt

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by sfshaza2** [comment]
Of course, this PR primarily looks fine. The only possible issue, is that we often run dartfmt with a maximum line length of 70 (or so) to avoid having the example code wrap when displayed on the site. Are we sure that this was not going on here?

Otherwise, LGTM.  :)

**Comment by mit-mit** [comment]
I ran it with the default line length. Is that not what we usual do?

**Comment by sfshaza2** [comment]
You'd have to check with Kathy for recent info, but we used to run it with
a default line length of 70, otherwise the code often wrapped in those code
blocks. But things may have changed.

**Comment by johnpryan** [comment]
Is this still necessary now that we've upgraded to 2.4?

**Comment by mit-mit** [comment]
Yes, see: https://travis-ci.org/dart-lang/site-www/jobs/551280797

But I think we can wait until @kwalrath is back to answer the line length question

**Comment by sfshaza2** [comment]
Agreed. This isn't urgent..

**Comment by kwalrath** [comment]
We don’t run dartfmt directly… instead, we use `tool/dartfmt.sh`. When I run that, I see only one diff. I’m looking into it now…

**Comment by kwalrath** [comment]
Only one file needs to change due to dartfmt. I’ve fixed that in #1717.

**Pull request closed without merging**
