### PR TITLE
refactor(Null safety): fix typo about number of core design principles

### PR DESCRIPTION
**Pull request by dancer1325**
* Fix a typo about number of core design principles mentioned afterwards

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn’t contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Review by parlough — CHANGES_REQUESTED** [review]
Thanks for the PR!

Before we can review and incorporate the change, you'll have to sign the Google CLA as outlined in the earlier PR comment with the same email as you committed with: https://github.com/dart-lang/site-www/pull/5154#issuecomment-1707817926

Once that is complete, we'd be happy to take another look. Thank you!

**Comment by dancer1325** [comment]
> Thanks for the PR!
> 
> Before we can review and incorporate the change, you'll have to sign the Google CLA as outlined in the earlier PR comment with the same email as you committed with: [#5154 (comment)](https://github.com/dart-lang/site-www/pull/5154#issuecomment-1707817926)
> 
> Once that is complete, we'd be happy to take another look. Thank you!

Hi @parlough 

* Already signed the CLA -- Sorry for that ... --
* I was not able to check that all was fine, since I couldn't relaunch the github action which triggers the 'build.yml'

**Comment by parlough** [comment]
Thanks for the response and I'm sorry about the back and forth... I re-ran the CLA check and it seems it's still failing.

Check the workflow for more information (https://github.com/dart-lang/site-www/pull/5154/checks?check_run_id=16833416591), but it seems the commit was made with your hidden GitHub email. The workflow failure explains more, but you may need to add that to your CLA or recommit with the email you signed the CLA with.

**Review by parlough — APPROVED** [review]
Thanks for this, looks good to me!

Sorry about the delay and the CLA issues.

**Pull request merged**
