### PR TITLE
Added a Dart logo in (Header) README.md file.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
**Changes**
Added a Dart logo in (Header) README.md file.
Resource File link - https://github.com/dart-lang/site-shared/blob/master/src/_assets/image/dart/logo/64.png

**Before Changes**

**After Changes**

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
@kwalrath @parlough

**Review by parlough — APPROVED** [review]
Thanks for the PR @Pradumnasaraf! I think including the icon adds some nice character and color to the README. I'll leave the decision to merge this to @kwalrath though :)

**Comment by Pradumnasaraf** [comment]
@parlough, Thanks for your reply :)

**Comment by Pradumnasaraf** [comment]
Hey @kwalrath, look like you forgot to merge this :)

**Comment by kwalrath** [comment]
> Hey @kwalrath, look like you forgot to merge this :)

Didn't forget! Just was busy. LGTM!

**Comment by kwalrath** [comment]
Uh oh, I just saw https://github.com/dart-lang/language/pull/1856. I'll chat with @mit-mit about this today.

**Comment by Pradumnasaraf** [comment]
> > Hey @kwalrath, look like you forgot to merge this :)
> 
> Didn't forget! Just was busy. LGTM!

Haha, Thank you for the effort  @kwalrath.

**Comment by kwalrath** [comment]
The upshot was that since site-www depends on site-shared anyway, it's OK to depend on it for this icon. But in general, repos should be self-contained.

**Comment by Pradumnasaraf** [comment]
> The upshot was that since site-www depends on site-shared anyway, it's OK to depend on it for this icon. But in general, repos should be self-contained.

Indeed, I think of adding the file itself to the repo, but after seeing other dart and flutter repos I saw a common practice of using logos and images from a common repo. so I followed that way :). Please tell me if you need it in another way?

**Pull request merged**
