### PR TITLE
Fix examples for Dart 2.5 Uint8List changes

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kwalrath** [comment]
It looks like you need to rerun tool/dartfmt.sh. We use <80 char line lengths due to the size of the code boxes.

**Comment by kevmoo** [comment]
> lgtm, but maybe @domesticmouse or @johnpryan should take a look, too?

PTAL – and PLEASE do a squash-merge on this. or else history will look crazy funky

**Comment by kwalrath** [comment]
> PTAL – and PLEASE do a squash-merge on this. or else history will look crazy funky

Sure thing. I *always* squash-merge.

**Comment by kwalrath** [comment]
Ugh, now you need to run /tool/refresh-code-excerpts.sh. Sorry… I didn’t know this was visible code.

**Comment by domesticmouse** [comment]
I’m assuming we are holding this PR until dart 2.5 lands?

**Comment by kwalrath** [comment]
Strangely, the stable build is green but the [dev build](https://travis-ci.org/dart-lang/site-www/jobs/557672868) is not. I’d expect both to be green before we can merge this.

**Comment by kevmoo** [comment]
It's LESS broken than the last dev build, though -
https://travis-ci.org/dart-lang/site-www/jobs/557931918

**Comment by kevmoo** [comment]
> Strangely, the stable build is green but the [dev build](https://travis-ci.org/dart-lang/site-www/jobs/557672868) (which we allow to fail) is not. I’d expect both to be green before we can merge this.

https://github.com/dart-lang/site-www/pull/1763 Fix!

**Pull request merged**
