### PR TITLE
Migrate Iterable Collections Codelab to Null Safety

### PR DESCRIPTION
**Pull request by miquelbeltran**
Continuing the work from the https://github.com/dart-lang/site-www/pull/2805 PR.

This PR adds the migrated version of the Iterable Collections codelab in the `iterables_migrated.md`, following the migration guide.

This PR is split in two different commits:

- The first commit is just a copy of the original `iterables.md` to `interables_migrated.md`
- The second commit includes all the modifications:
1. Update the example excerpts path.
2. Add the `null_safety-true` flag to the dartpad examples
3. Update code in dartpad examples to be null safety compatible.

You can see that many of the checks if the output was null has been removed, and instead, a catch for `UnimplementedError` has been added. This is to catch cases in which the learner forgot to remove the `TODO()` function call.

Live preview: https://mb-dart-dev-1.firebaseapp.com/codelabs/iterables_migrated

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Ping @kwalrath @RedBrogdon

**Comment by miquelbeltran** [comment]
I'm preparing a live version on firebase asap

**Comment by kwalrath** [comment]
Is the only visible change the switch from comments to TODO() in the embedded DartPads? If so, that's kind of amazing!

**Review by kwalrath — APPROVED** [review]

**Comment by miquelbeltran** [comment]
Yes, all the original code examples were null safe already, most of the changes are on the validation code for the exercises

**Pull request merged**
