### PR TITLE
[1.x] Dart language-version menu for switching between site versions

### PR DESCRIPTION
**Pull request by chalin**
Cherry picked #724 + some minor adjustments.

Staged at https://dartlang-org-staging-0.firebaseapp.com

---

The dropdown looks like this:

> screen shot 2018-04-05 at 17 37 22

cc @kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
Love it!

**Comment by kwalrath** [comment]
It looks great! Let's hold off on this until @anders-sandholm tells us it's OK to switch. (If it is, then of course we'll need to commit #752 as well.)

**Comment by anders-sandholm** [comment]
LGTM. 

Except for the URL in the address bar (and the dropdown), it is hard to tell whether you're looking at the 1.x or 2 version of the site. It might make sense to throw in a banner for the entire 1.x site saying something along the lines of "This page is showing old contents for Dart 1.24. Go to dartlang.org for the latest Dart 2 related contents."

**Comment by chalin** [comment]
@anders-sandholm - I've added an "Add banner to 1x"  work item to #654 to track that.

**Comment by chalin** [comment]
- #764 added the banner w/ conditional logic to ensure that it will show up only after the server switch.
- @kwalrath and @anders-sandholm have given a thumbs up, so I'm merging this. Like for the banner, the menu will only appear after the switch.

**Pull request merged**
