### PR TITLE
Include incompatible linter rules

### PR DESCRIPTION
**Pull request by parlough**
Progresses towards https://github.com/dart-lang/site-www/issues/3222

**Hosted:** https://parlough-dart-dev.web.app/tools/linter-rules

**Example:** https://parlough-dart-dev.web.app/tools/linter-rules#unnecessary_final

cc @pq

### CODE REVIEW

**Review by kwalrath — COMMENTED** [review]
The incompatible rules are likely to be overlooked. Could we put them up above? And maybe drop the code font. Something like this (compare to https://parlough-dart-dev.web.app/tools/linter-rules#unnecessary_final):

### unnecessary_final

Don’t use `final` for local variables.

**Incompatible rules:** [prefer_final_locals](), [prefer_final_parameters]()

#### Details

...

**Comment by kwalrath** [comment]
We might want to mimic the formatting in Effective Dart:

image

**Comment by parlough** [comment]
@kwalrath You make a good point and thanks for the suggestions. I'll try out a few layouts before sending this back to you. Thanks!

**Comment by pq** [comment]
Love this direction.  Thanks for pushing on it @parlough!

**Comment by parlough** [comment]
Getting a bit frustrated by extra spaces, but hoping to have everything sorted soon:

image

**Comment by parlough** [comment]
Thanks for all of the feedback! I've gone ahead and updated the staged version, let me know what you think.

**Review by kwalrath — APPROVED** [review]
Looks great! And I like how you've put the code into its own file.

**Review by pq — APPROVED** [review]
💎 💎 💎

**Comment by pq** [comment]
FWIW: I *just* pushed an updated `rules.json`.  Not sure if you need to manually sync to that -- If I could only remember where that bit lives I'd look for myself! 🤔

**Comment by parlough** [comment]
@pq Thanks, I'll update that in a separate PR. I am still meaning to look into a better process for that, but haven't had the chance yet. I'm considering a release action on the linter repo that can handle all of the generation on that end as well as an update here, but I'll let you know when I make progress on that front.

**Comment by parlough** [comment]
@pq You mentioned you just pushed an update. I don't think I see see this anywhere. Are you pushing somewhere besides https://github.com/dart-lang/linter/tree/gh-pages?

**Comment by pq** [comment]
Ah!  So sorry, I committed but forgot to push.  There now:

https://github.com/dart-lang/linter/commit/8b25ecba15602f98540d0ef0e7ea721c500b864f#diff-c8b3b028897f729f60cb641925c4c21dbc4af2626eecbb0c4e215c40fd1f58a2

**Pull request merged**
