### PR TITLE
Fix the analysis results breaking the build

### PR DESCRIPTION
**Pull request by mit-mit**
We promoted a new beta build, so now these changes from dev (https://github.com/dart-lang/site-www/pull/3675) are needed in beta

### CODE REVIEW

**Review by parlough — APPROVED** [review]
Looks good to me. Might want to wait until after the freeze, but since it's minor it should be fine to merge if needed.

**Comment by mit-mit** [comment]
When do we expect to unfreeze? PR template said yesterday :-)

**Comment by kwalrath** [comment]
> When do we expect to unfreeze? PR template said yesterday :-)

I'm not sure (will know tomorrow), but sometime this week. (It's easy to miss, but the PR template says "the week of December 13.")

**Comment by mit-mit** [comment]
OK; Thursday is my last day, but feel free to merge any of my PRs while I'm gone.

**Comment by kwalrath** [comment]
> OK; Thursday is my last day, but feel free to merge any of my PRs while I'm gone.

Thursday is my last day, too (not forever, but until January 10). I've committed this, and I'm going to see how the build goes. After that, I might commit your other PR.

**Pull request merged**
