### PR TITLE
Update text on "pub cache repair"

### PR DESCRIPTION
**Pull request by jonasfj**
* Avoid talking about the `packages/` folder as something that contains symlinks.
 * Mention `.packages` and how your editor might follow references in this file.

### CODE REVIEW

**Comment by jonasfj** [comment]
It's was rather random that I noticed this... I suppose it's possible that all the docs on `pub` could use a quick review. The example above on how to install `barback` probably isn't ideal either. We could change the example to install the `test` package maybe... anyways, when we have a rainy day maybe.

**Comment by kwalrath** [comment]
Good catch! I wonder if we need to get into such detail. Maybe we could just say:

<dd>It's possible for packages in your pub cache to change or break.
For example, you might accidentally edit or delete a file in the pub cache.
The <code>pub cache repair</code> command performs a clean reinstall of all
hosted and git packages in the system cache.</dd>

**Comment by kwalrath** [comment]
My IDE gives me warnings if I try to do that. :) (Although it does give me the option of saving the file anyway.) Your IDE doesn't warn you?

**Comment by jonasfj** [comment]
I don't think vscode gave me a warning... If so I happily ignored it :)

Anyways, I'm perfectly okay with either solution... Feel free to merge this
or close it and write a different text..

Main point of this PR was to ensure we cleaned up the worst legacy..

**Comment by kwalrath** [comment]
Sorry for the delay on this. I aim to commit this PR by EOW.

**Comment by kwalrath** [comment]
I'm proposing some text that doesn't mention `.packages`.

**Pull request merged**
