### PR TITLE
Show M1 SDKs in stable

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by parlough** [comment]
@mit-mit Next time, can you target changes to a site-www branch next time now that automatic previews are enabled. Or perhaps we can expand to allow previews from collaborator branches as well?

**Comment by mit-mit** [comment]
This change doesn't show anything in preview (it needs the stable SDK to actually be deployed), so I deliberately didn't target site-www...

**Comment by mit-mit** [comment]
But it would actually be useful to have it in preview come to thing of it, so that we can validate before we merge it... Will create a new one.

**Comment by mit-mit** [comment]
replaced by https://github.com/dart-lang/site-www/pull/3550

**Pull request closed without merging**
