### PR TITLE
image when on mobile

### PR DESCRIPTION
**Pull request by FaisalAbid**
@mit-mit

### CODE REVIEW

**Comment by mit-mit** [comment]
Maybe I'm missing something, but will this not cause both the video and the image to show when on mobile?

**Comment by FaisalAbid** [comment]
the `'d-sm-none d-md-block'` means on narrow dissapear and md and above show up

and vice versa for `d-sm-block d-md-none`

**Comment by kwalrath** [comment]
> Maybe I'm missing something, but will this not cause both the video and the image to show when on mobile?

It doesn't look like it does: https://dartlang-org-staging-1.firebaseapp.com

**Comment by mit-mit** [comment]
Got it; did a bit of testing and seems to work great

**Pull request merged**
