### PR TITLE
Add scorecard results badge

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]
Thanks for adding the badges!

**Comment by mit-mit** [comment]
When I click the badge I just get a big JSON blog in my browser window. Is there some more formatted rendering of the score cards?

**Comment by parlough** [comment]
I'm not currently aware of anywhere, but perhaps @godofredoc knows?

**Comment by godofredoc** [comment]
> I'm not currently aware of anywhere, but perhaps @godofredoc knows?

Opened a feature request to the scorecards team a few days ago to show a human readable report. https://github.com/ossf/scorecard-webapp/issues/206

**Comment by mit-mit** [comment]
Thanks! For now this LGTM

**Review by mit-mit — APPROVED** [review]

**Pull request merged**
