### PR TITLE
redirects for editor and eclipse

### PR DESCRIPTION
**Pull request by kevmoo**
A couple of catch-alls that handle many of the remaining 404s

Not going to bother w/ staging – did verify locally

### CODE REVIEW

**Comment by filiph** [comment]
Thanks. We still use a spreadsheet to generate the [spreadsheet](https://docs.google.com/spreadsheets/d/1rQvqPLIYwi3MPA8WiXSEO-lAxd36A7z0E4Z3GhtCqPY/edit#gid=1550556517&vpid=A1) to generate the redirects, as I expect there will still be more things to add and a spreadsheet makes it a bit easier to keep track of things. I added your changes to the spreadsheets so it's in sync.

**Comment by Sfshaza** [comment]
Thanks, Filip, you beat me to it!

I was going to add the top 10 redirects from your weekly report on Friday,
Kevin. I haven't looked, but does this obviate that need?

**Comment by filiph** [comment]
It doesn't. It's just 3 redirects, all about "eclipse" URLs. Shams, feel free to add more and I can update.

**Comment by Sfshaza** [comment]
OK, I will do so, but later this week, if that's OK.

**Comment by filiph** [comment]
Sure!

**Pull request merged**
