### PR TITLE
Update the color of good/bad boxes.

### PR DESCRIPTION
**Pull request by isoos**
Updated font and position along the color updates.

### CODE REVIEW

**Comment by kwalrath** [comment]
I'm not crazy about the new "green". Does it look almost blue to you?
[old](https://dartlang-org-staging-0.firebaseapp.com/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores) |  [new](https://sz-www-1.firebaseapp.com/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)

**Comment by kwalrath** [comment]
I like the new position of the lettering, but it seems much less legible (too small & spidery).

**Comment by mit-mit** [comment]
@kwalrath did we get a resolution to this?

**Comment by kwalrath** [comment]
> @kwalrath did we get a resolution to this?

No, I was planning to talk about it in today's meeting. (I should send out an agenda...)

**Pull request merged**
