### PR TITLE
Add missing example in add-elements

### PR DESCRIPTION
**Pull request by smolck**
See #1807.

### CODE REVIEW

**Comment by kwalrath** [comment]
Did you mean to upload this? It looks like this change just comments out the rest of the file. We need to embed a DartPad that references the new gist. Once you add that, I'll stage the page.

**Comment by smolck** [comment]
> Did you mean to upload this? It looks like this change just comments out the rest of the file. We need to embed a DartPad that references the new gist. Once you add that, I'll stage the page.

Oops! Sorry about that! I misunderstood how the DartPad was embedded...fixed it.

However, when I tested it through the browser's dev tools (inserted the new id in an already-embedded DartPad), it didn't work. That's probably why the example was removed in the first place (seems that way from the comments left behind).

**Comment by smolck** [comment]
> You can see it staged here: https://kw-staging-dartlang-2.firebaseapp.com/tutorials/web/low-level-html/add-elements

@kwalrath Does the code show up in the DartPad for you? When I visit the staged page it is just an empty DartPad with the text "UI Output" in it.

**Comment by kwalrath** [comment]
Yes, it works for me, although I have to run it to get the output. Here's what I see:

Before clicking **Run**:
image

After clicking **Run**:
image

**Comment by kwalrath** [comment]
Can you see the code at https://gist.github.com/kwalrath/aab6ad8c04d161458d32161ea6e87a97? I believe it's a public gist. Is it possible you've loaded gists so much in the past hour that you've been temporarily shut out?

Also... It looks like we need to do a couple of things that I could/should file as issues:

* Add an include for the DartPad troubleshooting page high up in this page (probably deleting the include that's lower in this page).
* Add info to the DartPad troubleshooting page about what happens if you load too many DartPads and run into GitHub rate-limiting. (Rare unless you're repeatedly reloading a page full of DartPads.)

**Comment by smolck** [comment]
> Can you see the code at https://gist.github.com/kwalrath/aab6ad8c04d161458d32161ea6e87a97? I believe it's a public gist. Is it possible you've loaded gists so much in the past hour that you've been temporarily shut out?

It appears to be a problem with Brave or DartPad itself. Everything works fine in FireFox Dev Edition and IOS Safari. I may need to look into why things don't show with Brave.

**Comment by kwalrath** [comment]
Ah, that's a known problem. Brave disables cookies, which disables localStorage, which DartPad depends on.

**Pull request merged**
