### PR TITLE
Add a new dart book

### PR DESCRIPTION
**Pull request by JHBitencourt**
Would like to add my new published book to this page. The book is written in Portuguese 🇧🇷  though.

### CODE REVIEW

**Comment by parlough** [comment]
@JHBitencourt It's great to see another book about Dart in other languages and I love the cover. Great work!

What do you think about including a short English description as well separated by a `<br>` which mentions the language? That way it has some info for other users of the site and is maybe easier to search for if someone is trying to specifically find "Portuguese Dart book" or something along those lines. 

Here's a potential example, mostly directly translated:

```  
desc: "..... no aprendizado de Dart.<br>Fundamentals, practice, concepts, and more. Embark on a journey of learning Dart in Portuguese."
```

**Comment by JHBitencourt** [comment]
@parlough sure! We can do that, no problem at all.
I did like this inspired by the [flutter books page](https://docs.flutter.dev/resources/books) that contains a french book listed.

What about:

```
desc: "Fundamentos, prática, conceitos avançados e tudo mais. Embarque neste livro que te guiará no aprendizado de Dart.<br>Fundamentals, practice, the concepts and everything. Embark on a journey of learning Dart in Portuguese."
```

**Comment by parlough** [comment]
@JHBitencourt That sounds good to me :)

**Review by parlough — APPROVED** [review]
Thanks so much for working on this book and for the PR, it's exciting!

**Pull request merged**
