### PR TITLE
Linking Brew, Choco and apt-get beta/dev instructions

### PR DESCRIPTION
**Pull request by domesticmouse**
I'd like to link the dart-lang/sdk wiki's "Installing beta and dev releases with brew, choco, and apt get" documentation to make it a lot easier to find. Thoughts?

### CODE REVIEW

**Comment by mit-mit** [comment]
I prefer the simplicity of excluding this from here (and then perhaps adding the link to "Want to install Dart with your OS’s package manager? Get Dart." on https://dart.dev/tools/sdk/archive), but it's not a strong preference...

**Comment by domesticmouse** [comment]
I’m happy to demote it to that page, if we change the description of the link on this page to cover the expanded scope.

**Comment by kwalrath** [comment]
@mit-mit & @athomas I think I found an error on the wiki page, so I just updated it. Please check [the diffs](https://github.com/dart-lang/sdk/wiki/Installing-beta-and-dev-releases-with-brew,-choco,-and-apt-get/_compare/c5782f7aebbd179d02b6f9901dedb3480460b3c9...7b81d156d028faf3e0cee497610a2f6bc417e2c7).

**Comment by kwalrath** [comment]
> I prefer the simplicity of excluding this from here (and then perhaps adding the link to "Want to install Dart with your OS’s package manager? Get Dart." on https://dart.dev/tools/sdk/archive), but it's not a strong preference...

Since this is at the bottom of the page, I think it's fine to link to the wiki here. (We might also want a link on the archive page.)

**Comment by kwalrath** [comment]
LGTM if my changes LGTY

**Comment by domesticmouse** [comment]
LGTM2 =)

**Comment by domesticmouse** [comment]
Weird, travis is showing as pending here, but green if you click through the `Details` link. How do computers work?

**Comment by athomas** [comment]
> @mit-mit & @athomas I think I found an error on the wiki page, so I just updated it. Please check [the diffs](https://github.com/dart-lang/sdk/wiki/Installing-beta-and-dev-releases-with-brew,-choco,-and-apt-get/_compare/c5782f7aebbd179d02b6f9901dedb3480460b3c9...7b81d156d028faf3e0cee497610a2f6bc417e2c7).

LGTM, I made my own edit to fix some minor inconsistencies:
https://github.com/dart-lang/sdk/wiki/Installing-beta-and-dev-releases-with-brew,-choco,-and-apt-get/_compare/7b81d156d028faf3e0cee497610a2f6bc417e2c7...4ead9e7b7244ebd6bcd46cbd426799150c0a5abf

**Pull request merged**
