### PR TITLE
Update language-tour.md

### LINKED ISSUE #572: In Dart 2, first arg to assert() can't be a function
See dart-lang/sdk#30326.

I think the only affected doc is the last paragraph of https://www.dartlang.org/guides/language/language-tour#assert.

### PR DESCRIPTION
**Pull request by anders-sandholm**
Update assert description to only allow expressions of type boolean (and not allow functions).
Fixes #572.

### CODE REVIEW

**Comment by Sfshaza** [comment]
LGTM

**Comment by kwalrath** [comment]
Should we make a point of updating the other branch to say this change will be coming? (If so, we shouldn't close the bug, but note that the dart 1 docs should be updated.)

**Comment by chalin** [comment]
> Should we make a point of updating the other branch to say this change will be coming?

It has been my understanding that we only make changes to the 1.x branch if something is "broken".

**Comment by anders-sandholm** [comment]
Merging then.

**Pull request merged**
