### PR TITLE
Remove int exponent example from language tour

### PR DESCRIPTION
**Pull request by Daniel-Yonkov**
Issue reference #4099

### CODE REVIEW

**Comment by parlough** [comment]
Thanks for removing that, looks good to me! Once you sign the CLA as outlined in https://github.com/dart-lang/site-www/pull/4100/checks?check_run_id=6895673395, I will go ahead and merge this :)

**Review by parlough — CHANGES_REQUESTED** [review]
This snippet is pulled from a section of a Dart file. Can you remove the line there as well: https://github.com/dart-lang/site-www/blob/main/examples/misc/lib/language_tour/built_in_types.dart#L9

Thanks!

**Comment by Daniel-Yonkov** [comment]
@parlough  - Addressed the changes and signed the CLA but seems to not have updated... I think I have used the same email as in the commit

**Review by parlough — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
