### PR TITLE
Add null safety placeholder

### PR DESCRIPTION
**Pull request by kwalrath**
Addresses #2312.

Staged:
https://kw-staging-dartlang-2.firebaseapp.com/null-safety
https://kw-staging-dartlang-2.firebaseapp.com/null-safety/migration-guide

### CODE REVIEW

**Comment by mit-mit** [comment]
Place holder LGTM, but I don't think we want a "migration guide" this soon. That may be misconceived as a migration call-to-action, and that's too soon.

**Comment by kwalrath** [comment]
The migration guide is just a temporary redirect to the main null safety page. I thought that URL was mentioned in command output, so we needed that redirect?

**Comment by mit-mit** [comment]
I don't know if that's the case or not. But if it is the case, I think the Url should go to an actual placeholder page for migration, which should say something like "As part of the final null safety feature, we plan on making a migration tool available. At the current stage, with null safety still in preview, we do not recommend doing anything but test migration"

**Comment by kwalrath** [comment]
ptal

**Comment by mit-mit** [comment]
Looks good, thanks!

**Pull request merged**
