### PR TITLE
Update analyzer diagnostic messages for latest SDK changes

### PR DESCRIPTION
**Pull request by parlough**
Represents the latest changes and additions to the diagnostic messages as of https://github.com/dart-lang/sdk/commit/548cba8d84d1f3fd059d5db5b9f21247c26208a0#diff-d1e3ffc3a6f5e620a6dd01422e8bb981a19204bebc26a9e29a6f408dead5000f

**Staged:** https://parlough-dart-dev.web.app/tools/diagnostic-messages

Fixes https://github.com/dart-lang/site-www/issues/3361

### CODE REVIEW

**Review by kwalrath — CHANGES_REQUESTED** [review]
Looks great!

I did, however, find an issue that was already in the page: in 2 places, links to definite assignment are malformed. I caught this by searching for `][` in the rendered page.

Could you please fix those links in this PR, @parlough? Then @bwilkerson can apply your fixes to the SDK copy.

Thank you!

**Comment by parlough** [comment]
@kwalrath Are these the two you were referring to?

**Comment by kwalrath** [comment]
> @kwalrath Great catch! Are these the two you were referring to?

Yep, you got them. Thanks!

**Comment by bwilkerson** [comment]
Wow, that was fast! Thanks.

**Pull request merged**
