### PR TITLE
Document how to control analytics

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/dart-lang/sdk/issues/39233

### CODE REVIEW

**Review by kwalrath — APPROVED** [review]
LGTM after my tweaks to make the spacing more compact

**Comment by mit-mit** [comment]
Thanks! @devoncarew can you confirm that this single setting controls all analytics upload from the SDK?

**Comment by devoncarew** [comment]
> Thanks! @devoncarew can you confirm that this single setting controls all analytics upload from the SDK?

Yup, those are the two that control the analytics we send.

**Comment by iamchathu** [comment]
@mit-mit 

`dart --disable-analytics`

Does show help and no confirmation if it disabled or not. Maybe the option doesn't work

**Comment by mit-mit** [comment]
@iamchathu if you have a repro of that, please open an issue with detailed steps. Please include the output of `dart --version`, and which OS you are running.

https://github.com/dart-lang/sdk/issues

**Comment by mit-mit** [comment]
Oh, got a repro in dev channel. Filed an issue for that: https://github.com/dart-lang/sdk/issues/44968

**Pull request merged**
