### PR TITLE
Copy edit & link to cheatsheet codelab

### LINKED ISSUE #1619: Link to new codelab
dart.dev/codelabs should link to dart.dev/codelabs/dart-cheatsheet.

### PR DESCRIPTION
**Pull request by kwalrath**
Fixes #1619 

Staged:
https://kw-www-dartlang-1.firebaseapp.com/codelabs
https://kw-www-dartlang-1.firebaseapp.com/codelabs/dart-cheatsheet

### CODE REVIEW

**Comment by kwalrath** [comment]
@RedBrogdon it occurred to me that we should include the actual cheatsheet in this codelab — or link to another page that's just the cheatsheet. What do you think?

**Comment by kwalrath** [comment]
It also occurred to me that we should be clearer up front about the audience. If it includes beginning Dart developers, then we should offer more help with the API. (Maybe we should do that even if we explicitly _don't_ want Dart learners.)

**Comment by RedBrogdon** [comment]
> @RedBrogdon it occurred to me that we should include the actual cheatsheet in this codelab — or link to another page that's just the cheatsheet. What do you think?

Good idea. My vote would probably be for a separate page, since the "I want to quickly scan and remind myself of the list of features" and "I want to actively practice those features" audiences would likely be pretty distinct.

**Comment by kwalrath** [comment]
> > @RedBrogdon it occurred to me that we should include the actual cheatsheet in this codelab — or link to another page that's just the cheatsheet. What do you think?
> 
> Good idea. My vote would probably be for a separate page, since the "I want to quickly scan and remind myself of the list of features" and "I want to actively practice those features" audiences would likely be pretty distinct.

OK, I'm going to update this PR with that page, so that the name makes sense.

**Comment by kwalrath** [comment]
I've uploaded the cheatsheet page but haven't put it in the sidenav, for a couple of reasons:

* I'm not crazy about how I formatted it. I'd like it to be visible in a single page, but that'd take a while to make happen.
* There's not a one-to-one correspondence between items covered in the cheatsheet and the items covered in the codelab. I'd like to make them agree more.

I've updated the staging server:

https://kw-www-dartlang-1.firebaseapp.com/codelabs
https://kw-www-dartlang-1.firebaseapp.com/codelabs/dart-cheatsheet
https://kw-www-dartlang-1.firebaseapp.com/guides/language/cheatsheet

/cc @mehmetf

**Comment by kwalrath** [comment]
I'm going to merge this and put your suggestions for the cheatsheet in a new issue. Thanks for the content and the reviews!

**Pull request merged**
