### PR TITLE
Update windows installation in get-packages

### PR DESCRIPTION
**Pull request by Sameerkash**
Related  to #2617, 

Added alert to use administrative privileges when installing dart-sdk on windows 

reference - #2853

### CODE REVIEW

**Review by kwalrath — CHANGES_REQUESTED** [review]
Could you please undo/update the changes to packages.md & formatting.md?

**Comment by Sameerkash** [comment]
> Could you please undo/update the changes to packages.md & formatting.md?

Ah Sorry about that, I'll rebase from master and push

**Comment by Sameerkash** [comment]
@kwalrath fixed the conflicts! please have a look

**Comment by Sameerkash** [comment]
@kwalrath could you please review the failing test?

**Comment by kwalrath** [comment]
> @kwalrath could you please review the failing test?

I don't think it's particular to your PR... Travis CI wasn't working for a while, so we didn't realize that some tests stopped passing a few PRs ago.

**Review by kwalrath — APPROVED** [review]
LGTM. Thanks, @Sameerkash!

**Pull request merged**
