### PR TITLE
Fixing links for Linux install

### PR DESCRIPTION
**Pull request by Sfshaza**
Staged:  https://sz-www-1.firebaseapp.com/install/linux

Please review, @whesse

### CODE REVIEW

**Comment by Sfshaza** [comment]
One more comment: 

Fixes https://github.com/dart-lang/site-www/issues/284

**Comment by whesse** [comment]
LGTM.  Is the addition of the two helper files intentional? If I haven't copied the stable files yet, I'll do it soon.

**Comment by kwalrath** [comment]
I don't think the packages files should go in there. (Not a big deal... I'll just remove them if you add them.)

**Comment by Sfshaza** [comment]
A bit unsure why running the code created two new files. Leaving them here, for now.

**Pull request merged**
