### PR TITLE
Add fallback image to main page video(dart-lang#1889)

### PR DESCRIPTION
**Pull request by hugekoala**
Related to #1889

### CODE REVIEW

**Comment by kwalrath** [comment]
LGTM once we get a signed CLA from @hugekoala.

@johnpryan, LGTY?

**Comment by johnpryan** [comment]
Yep this looks good to me.

**Comment by madmonl** [comment]
Hey guys, sorry for late reply, here from my main account back,
Will send the PR here again from this account and close the current one that I openned on hugekoala account on sunday.
Sorry for the mess (sometimes on work's computer).
Feel free to merge if you want.

**Comment by kwalrath** [comment]
Merged #1917 instead

**Pull request closed without merging**
