### PR TITLE
Add Russian website link

### PR DESCRIPTION
**Pull request by iboldurev**

### CODE REVIEW

**Comment by iboldurev** [comment]
@googlebot I signed it!

**Comment by jonasfj** [comment]
I have no context on this.

**Comment by iboldurev** [comment]
@jonasfj thanks for the feedback

**Comment by kwalrath** [comment]
@iboldurev can you tell us why this site is helpful to Russian devs? I expected it to be in Russian, but the pages I saw were English.

**Comment by iboldurev** [comment]
@kwalrath Hi, thanks for the question. Now we (the local community) are translating the site, and in the near future, of the site will be translated into Russian.
We want to help Russian developers to learn more about dart & flutter.

**Comment by kwalrath** [comment]
I'll be very happy to add you when you're a little further along. I'd like to see three things first:

* Repo links (e.g. the bug and source links on every doc page) point to your repo (assuming it's public), and not to dart-lang/site-www
* Russian language content on at least the first page
* Information somewhere about the effort to translate the site and how people can contribute

Does that sound reasonable, @iboldurev? I really appreciate that you're building and serving this website. Getting started with the website build can sometimes be a challenge!

**Comment by iboldurev** [comment]
Hey, @kwalrath yes, I agree with you

I updated the site version
- added translations for the main page, and a few more
- added a link to the repository where you can add changes (https://github.com/iboldurev/dart-lang)
- added a page for information how to help with the translation

I will wait for your feedback

**Comment by kwalrath** [comment]
It's looking good! A couple of comments:

* The issue (bug symbol) links don't seem to work because your repo doesn't have Issues enabled.
* I don't see the translated content in your repo.

Could you please enable issues and commit the translations?

Thanks!

**Comment by iboldurev** [comment]
Hi @kwalrath, thanks for the help with the bug icon, now I fix it, about translations so they are in develop branch. (https://github.com/iboldurev/dart-lang/tree/develop)

**Comment by kwalrath** [comment]
Cool! Could you make the document icons take people to the develop branch instead of the master branch?

**Comment by kwalrath** [comment]
Not a big deal, but you might want to also use the develop branch instead of the master branch in the bug template.

Before:
Page source: https://github.com/iboldurev/dart-lang/tree/master/src/platforms.md

After:
Page source: https://github.com/iboldurev/dart-lang/tree/develop/src/platforms.md

**Comment by iboldurev** [comment]
@kwalrath Now I will transfer everything to the master

**Comment by iboldurev** [comment]
@kwalrath done, I merged everything into a master and will continue to work only in it

**Pull request merged**
