### PR TITLE
append link to dart ru docs

### PR DESCRIPTION
**Pull request by geooooo**

### CODE REVIEW

**Comment by parlough** [comment]
Hi @geooooo, thanks for the contribution! It's great to see documentation in other languages. Before we run tests or include this change you'll need to sign the Google CLA as outlined by the GitHub action result [here](https://github.com/dart-lang/site-www/pull/3764/checks?check_run_id=4819684596).

I also have a few questions about the site. Do you know if the site is open source? Also it seems the home page and language tour are translated, which is fantastic, but are there plans to translate other portions of the site?

**Comment by geooooo** [comment]
Hi @parlough. Yes, I know that the site is open source. I am planing to translate other section and pages of docs.

**Comment by parlough** [comment]
Sorry, I meant is the Russian version open source? It's not necessarily required but it would be nice to be able to follow work done. For example, the Chinese site can be found here: https://github.com/cfug/dart.cn

**Comment by geooooo** [comment]
@parlough currently source of russian Dart docs placed here: https://github.com/geooooo/site-www/tree/ru-trans.
I'll create separate repository for ru site in future.

**Comment by geooooo** [comment]
Hi, @parlough ! I got CLA. Tell me, please, who can review this request ?

**Review by kwalrath — APPROVED** [review]

**Comment by kwalrath** [comment]
Thanks, @geooooo!

**Pull request merged**
