### PR TITLE
add bullet to non selected states and remove hand pointer

### PR DESCRIPTION
**Pull request by FaisalAbid**

### CODE REVIEW

**Comment by FaisalAbid** [comment]
Staged: https://kw-staging-dartlang-2.firebaseapp.com

**Comment by FaisalAbid** [comment]
@mit-mit

**Comment by mit-mit** [comment]
Look-and-feel in staging LGTM!

@kwalrath can you find someone to review the implementation?

**Comment by kwalrath** [comment]
@johnpryan could you review the implementation?

**Comment by johnpryan** [comment]
To me, the pointer cursor makes sense but I'm fine taking it out.

**Pull request merged**
