### PR TITLE
Add diagnostic messages and linter rules to sidebar

### PR DESCRIPTION
**Pull request by parlough**
What do you think about adding these to the sidebar under "Static analysis"?

Closes https://github.com/dart-lang/site-www/issues/3222

### CODE REVIEW

**Comment by kwalrath** [comment]
It does seem about time to put our top page in the sidenav. :) And the linter page, as well.

/cc @bwilkerson @devoncarew @pq

**Comment by bwilkerson** [comment]
The one counterargument that I can think of is one of the ones we originally had for not putting it there: it seems unlikely to be a page that anyone would want to navigate to other than as a result of wanting more information about a specific diagnostic, and in those cases they're likely to get there by either clicking in the IDE or the console (where they ran `dart analyze`). I don't know whether that's still a compelling reason.

**Comment by kwalrath** [comment]
> The one counterargument that I can think of is one of the ones we originally had for not putting it there: it seems unlikely to be a page that anyone would want to navigate to other than as a result of wanting more information about a specific diagnostic, and in those cases they're likely to get there by either clicking in the IDE or the console (where they ran `dart analyze`). I don't know whether that's still a compelling reason.

Yes, that occurred to me too. But it seemed weird to have a page with such heavy usage that isn't in the sidenav. We could put a query parameter on the sidenav if we want to count how many people use it :)

**Comment by parlough** [comment]
I can definitely understand your thinking. Anecdotally though I've found myself referring to the page quite a lot as there is a lot of great information present in the document. As we expand other analysis related documentation, it may be even more useful.

@kwalrath I've never set up UTM query parameters before. What should they look like in a situation like this?

Something like the following?

```
?utm_source=dartdev&utm_medium=sidenav&utm_campaign=diagnostics
```

**Comment by pq** [comment]
> I say we add them and track the usage.

💯 

I'm in favor.

This all looks great to me. 👍

**Comment by kwalrath** [comment]
> ```
> ?utm_source=dartdev&utm_medium=sidenav&utm_campaign=diagnostics
> ```

lgtm!

/cc @kevmoo

**Comment by kevmoo** [comment]
Since these are not redirects, we can use normal referral logic to track hits. No need for utm stuff...I think...

**Comment by kwalrath** [comment]
> Since these are not redirects, we can use normal referral logic to track hits. No need for utm stuff...I think...

How would we know which hits are from the sidenav?

**Comment by kevmoo** [comment]
> > Since these are not redirects, we can use normal referral logic to track hits. No need for utm stuff...I think...
> 
> How would we know which hits are from the sidenav?

We see links from pages on the site. We can size page X -> page Y

That info doesn't show up with a redirect, hence why we need the utm things

**Comment by kwalrath** [comment]
> > > Since these are not redirects, we can use normal referral logic to track hits. No need for utm stuff...I think...
> > 
> > 
> > How would we know which hits are from the sidenav?
> 
> We see links from pages on the site. We can size page X -> page Y

True, we can see that it isn't the landing page. And assume that it was the sidenav that resulted in the visit, although another possibility is in-site search.

**Comment by parlough** [comment]
Also some pages may separately link to these pages, for example a [page explaining diagnostics](https://github.com/dart-lang/site-www/issues/3650) or links from [mentions of specific diagnostics](https://github.com/dart-lang/site-www/issues/2579).

**Comment by kwalrath** [comment]
I'm going to merge this. We can always add utm stuff later.

**Review by kwalrath — APPROVED** [review]

**Pull request merged**
