### PR TITLE
Update landing page with latest text and images

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
@kwalrath can you check that I moved the content over correctly?
@FaisalAbid can you check that I didn't mess with the implementation?

**Comment by FaisalAbid** [comment]
Just tested and works good

**Comment by FaisalAbid** [comment]
Ah cool, i'll merge my branch with this when its in dash

**Comment by mit-mit** [comment]
@kwalrath I'm just going to merge this so Faisal can work off it. If you think we need text updates, just do a new PR!

**Pull request merged**
