### PR TITLE
Patch #1966

### PR DESCRIPTION
**Pull request by dhanushuUzumaki**

### CODE REVIEW

**Comment by kwalrath** [comment]
@wang-ories or @dhanushuUzumaki, did you have a way to select the checkbox by default?

**Comment by wang-ories** [comment]
@kwalrath  I already saw a similar way where the  the checkbox is selected  by default.

**Comment by dhanushuUzumaki** [comment]
@kwalrath The change needs to be done in dart-pad. I raise a PR today.

**Comment by dhanushuUzumaki** [comment]
@kwalrath I made the change to show it by default. But there is already a check which shows the web content by default if the gist has any web content. Do we want to override this behavior and show web content no matter the gist contains one or not?

**Comment by kwalrath** [comment]
> @kwalrath I made the change to show it by default. But there is already a check which shows the web content by default if the gist has any web content. Do we want to override this behavior and show web content no matter the gist contains one or not?

Nope, by default we shouldn't show web content unless there's an HTML file.

**Comment by dhanushuUzumaki** [comment]
> > @kwalrath I made the change to show it by default. But there is already a check which shows the web content by default if the gist has any web content. Do we want to override this behavior and show web content no matter the gist contains one or not?
> 
> Nope, by default we shouldn't show web content unless there's an HTML file.

This functionality is already in. So for the scope of #1966 I think adding this message will be enough.

**Pull request merged**
