### PR TITLE
Adopt Flutter's left sidebar structure and style.

### PR DESCRIPTION
**Pull request by isoos**
Copied files from Flutter's repository (no changes to them):
- `src/_assets/css/_bootstrap_config.scss`
- `src/_assets/css/_sidebar.scss`
- `src/_includes/sidenav.html`
- `src/_includes/sidenav-level-2.html`
- `src/_includes/sidenav-level-3.html`
- `src/_includes/sidenav-level-4.html`
- `src/_plugins/sidenav-active-entry-filter.rb`

The above files should be moved to the shared repository after this is merged (1-1 subsequent PRs for each repository).

Screenshot:
screen shot 2019-03-06 at 15 33 48

### CODE REVIEW

**Comment by isoos** [comment]
I can't invite reviewers, /cc @mit-mit, @filiph, @kwalrath

**Comment by kwalrath** [comment]
@isoos could you merge the Travis changes from #1384, so that this gets built?

**Comment by isoos** [comment]
> could you merge the Travis changes from #1384, so that this gets built?

@kwalrath: done.

**Comment by isoos** [comment]
It looks like the build passed. FYI: I have no write access.

**Pull request merged**
