### PR TITLE
Adds null_safe_examples, plus CI to format and analyze null safe code

### PR DESCRIPTION
**Pull request by RedBrogdon**
This PR adds opted-in null safe code to the repo, along with test infrastructure to make sure it's formatted and analyzed correctly. It does *not* add any snippets or code excerpts within the markdown files that consume this code. That'll be in a subsequent PR.

Details:

* Adds a new, root-level `null_safety_examples` directory, which contains a couple example projects for null safety, set up in a manner similar to the existing examples.
  - Also adds a single <code-excerpt> tag to the dart.dev/null-safety that uses code from this directory.
* Adds a --null-safety flag to `analyze-and-test-examples.sh` that will cause it to analyze null_safety_examples instead of the regular examples
  - Also removes old code working around the unified Dart tool's landing.
* Adds a --null-safety flag to `dartformat.sh` that will cause it to format the code in null_safety_examples instead of regular examples.
* Adds a --null-safety flag to `check_code.sh`, which it then passes on to `dartformat.sh`
* Updates travis configuration to include new jobs for each SDK version that call `check_code.sh` and `analyze-and-test-examples.sh` with these flags.
  - The stable and beta channel jobs are allowed to fail.

Also includes these changes, which were necessary to get stable channel tests passing in general:

* Updates several analyzer-results.txt files that no longer matched the output of the stable channel analyzer and were causing tests to fail
  - Also refreshes several code excerpts based on those files.

### CODE REVIEW

**Comment by RedBrogdon** [comment]
@kwalrath, this is ready for review at your leisure.

**Comment by RedBrogdon** [comment]
On second thought, I'm not quite done.

**Comment by RedBrogdon** [comment]
*Now* I'm done.

PTAL when you get the chance, @kwalrath. 😄

**Review by kwalrath — APPROVED** [review]
Wow. Thank you, @RedBrogdon!

**Pull request merged**
