### PR TITLE
Update diagnostic messages as of 2/26/22

### PR DESCRIPTION
**Pull request by parlough**
Staged: https://dart-dev--pr3858-misc-update-diagnost-xrot0h3x.web.app/tools/diagnostic-messages

Closes https://github.com/dart-lang/site-www/issues/3857

### CODE REVIEW

**Comment by sfshaza2** [comment]
Hi @parlough! @bwilkerson shared these changes with me in a Google doc last week. I made two passes over the page and Brian has already incorporated my edits. I just went through part of the page, and it looks ok. (I'm not sure I have the stamina to review the whole thing again.) Do you see any issues?

**Review by sfshaza2 — APPROVED** [review]
lgtm!

**Comment by parlough** [comment]
@sfshaza2 Ah I didn't know you already reviewed them this time. No need to review them again. Thanks so much!

**Comment by sfshaza2** [comment]
Thanks, @parlough! You rock. I appreciate your thoroughness!

**Pull request merged**
