### PR TITLE
Misc style updates.

### PR DESCRIPTION
**Pull request by isoos**
- info and alert boxes: background color and label color
- comment in code blocks
- table of content's title color
- striped tables do not need inner borders

### CODE REVIEW

**Comment by kwalrath** [comment]
Staged at URLs like https://sz-www-2.firebaseapp.com/guides/language/language-tour#keywords.

(Compare to https://dartlang-org-staging-0.firebaseapp.com/guides/language/language-tour#keywords.)

**Comment by kwalrath** [comment]
I've just updated the staged version to have the latest styles. @messi01 will try to take a look, but if that doesn't happen by tomorrow morning (Pacific), I'll probably do the review.

**Comment by messi01** [comment]
@isoos, there are some changes still needed to be made before this can be approved.

- info and alert boxes: background color and label color --> this color is closer to the expected color but it needs to be #4A4A4A
- comment in code blocks - approved
- table of content's title color - unsure what this refers too
- striped tables do not need inner borders - approved

**Comment by isoos** [comment]
> info and alert boxes: background color and label color --> this color is closer to the expected color but it needs to be #4A4A4A

@messi01: can you help me identify this one? I'm looking at `/guides/language/effective-dart/style` page, and the fist info box has a color of `#4a4a4a` there. The alert boxes are more often code blocks, which have their own coloring.
 
> table of content's title color - unsure what this refers too

The right sidebar has an in-page table of contents and navigation. Its header had a different color previously, now it is the default `4a4a4a`

**Comment by messi01** [comment]
> > info and alert boxes: background color and label color --> this color is closer to the expected color but it needs to be #4A4A4A
> 
> @messi01: can you help me identify this one? I'm looking at `/guides/language/effective-dart/style` page, and the fist info box has a color of `#4a4a4a` there. The alert boxes are more often code blocks, which have their own coloring.
> 
> > table of content's title color - unsure what this refers too
> 
> The right sidebar has an in-page table of contents and navigation. Its header had a different color previously, now it is the default `4a4a4a`

**Comment by messi01** [comment]
@isoos 

- info and alert boxes: background color and label color --> Sorry i didn't understand what this was referring to. This updates the main text color to #4A4A4A to reflect the design comps and looks good.

- table of content's title color - thank you for the reference. This also looks good and ready to go.

**Comment by messi01** [comment]
@isoos 

- info and alert boxes: background color and label color --> Sorry i didn't understand what this was referring to. This updates the main text color to #4A4A4A to reflect the design comps and looks good.

- table of content's title color - thank you for the reference. This also looks good and ready to go.

**Comment by messi01** [comment]
@kwalrath it seems like I still can't approve and commit this change. Could you approve on my behalf? Any suggestions on how to gain review approval access? Thanks!

**Pull request merged**
