### PR TITLE
Update Android Studio icon

### LINKED ISSUE #2942: Update Android Studio icon in tooling page
Page URL: https://dart.dev/tools/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/index.md

Description of issue: The tooling page includes the old Android Studio icon.

I tried to find a decent image of the new icon without the title, but all I could find is the following SVG. It has a circular white app background behind it which looked weird once added to the actual page:
https://raw.githubusercontent.com/JetBrains/android/f66ebcf239a05a3f7530f8f57acccf0730c22e77/adt-branding/src/artwork/androidstudio.svg

Perhaps internally you could reach out to someone who has the svg without the background

### PR DESCRIPTION
**Pull request by parlough**
Fixes #2942

### CODE REVIEW

**Comment by kwalrath** [comment]
It seems pretty huge (in pixels, that is). I'll try to follow up internally on whether there's a good SVG or a smaller copy.

**Comment by kwalrath** [comment]
I got an SVG! Not sure how to get it to you, though

**Comment by parlough** [comment]
@kwalrath Nice, that's perfect! Feel free to create a new PR or email it to me.

**Comment by parlough** [comment]
@kwalrath Looks good on my end, thanks for getting that svg!

**Review by kwalrath — APPROVED** [review]
LGTM. Thanks, @parlough!

**Pull request merged**
