### PR TITLE
Update nav

### PR DESCRIPTION
**Pull request by kwalrath**
Top nav is close, bottom nav is just a placeholder (based on the site-webdev footer, although we'll probably end up with something closer to the flutter.dev footer). Sidenav is still under discussion, but it's closer than what we currently have.

Staged: https://kw-www-dartlang-1.firebaseapp.com/guides

### CODE REVIEW

**Comment by sfshaza2** [comment]
The TBD links are causing problems with Travis. But the sidenav LGTM!

**Comment by kwalrath** [comment]
Thanks for the review! I'll make those sidenav links point somewhere...

**Comment by kwalrath** [comment]
Travis is happy.

**Comment by isoos** [comment]
Note: the logo is now removed from the footer.

**Comment by mit-mit** [comment]
I'm going to merge this so we can all work off a common base.

**Pull request merged**
