### PR TITLE
Update CoC e-mail

### PR DESCRIPTION
**Pull request by Hixie**
I'm just guessing but this seems out of date.

### CODE REVIEW

**Comment by parlough** [comment]
I’m not sure a dart.dev version of this email exists. Referring to @mit-mit who may know more.

**Review by sfshaza2 — APPROVED** [review]
lgtm

**Comment by Hixie** [comment]
Yeah looks like conduct@dart.dev doesn't go anywhere. We should fix that...

**Comment by kevmoo** [comment]
perhaps we should start by reverting this PR – DNS + email takes a bit to set up 😁

**Pull request merged**
