### PR TITLE
Added command for dart pub

### PR DESCRIPTION
**Pull request by Abhishek01039**
Added `dart pub` in the place of `pub`.

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@kwalrath 
can you please review this PR?
Thanks

**Comment by kwalrath** [comment]
I wonder... Can we just use `dart run` instead of `dart pub run`? (Have you tried it?)

/cc @mit-mit

**Comment by mit-mit** [comment]
Yes, you'll want `dart run`, not `dart pub run`.

The only exception is `pub run test`, which is just `dart test`.

**Comment by Abhishek01039** [comment]
ohh ! yes
@kwalrath 
my bad !

**Comment by Abhishek01039** [comment]
can you please review now ? @kwalrath

**Comment by kwalrath** [comment]
I'm closing this PR because we're going to need some more changes — removing most mentions of the `pub` tool, referring back to the dart-tool page (which is something I need to add to my PR #2804), changing the filename, and adding a redirect. I'll take care of it as part of my work on #2719 (which I've updated). I've also updated #2617 to reflect what we've learned about pub-run.md.

@Abhishek01039, your work helped us realize the need to transition this page over to the dart-tool work, so thank you for that, and sorry we couldn't use this PR!

Would you like to work on another page in #2617? (If so, I'll update #2617 to assign your chosen page to you; it didn't matter this time, but we should use that bug to keep track of who's working on what.)

**Comment by Abhishek01039** [comment]
Ah! ok, Thanks @kwalrath 
 I will look into this.

**Comment by kwalrath** [comment]
> Ah! ok, Thanks @kwalrath
> I will look into this.

Thanks for understanding!

**Pull request closed without merging**
