### PR TITLE
[WIP] Mocks for DartPad on the front page

### PR DESCRIPTION
**Pull request by RedBrogdon**
DO NOT MERGE

This PR includes an updated front page as well as two additional options showing where DartPad could be worked in:

* DartPad replaces the initial video
  - https://ab-dartlang-1.firebaseapp.com/index
* DartPad at the bottom of the page
  - https://ab-dartlang-1.firebaseapp.com/index2
* DartPad in the middle of the page
  - https://ab-dartlang-1.firebaseapp.com/index3

No work has been done to create an appropriate gist. This is just about where the editor could go.

### CODE REVIEW

**Comment by kwalrath** [comment]
I’m still seeing the initial video in https://ab-dartlang-1.firebaseapp.com/index.

Also, we’d talked about giving the ability to swap between the video and DartPad. Did that turn out to be impractical?

**Comment by RedBrogdon** [comment]
It did turn out to be impractical, but I mocked it anyway.

There's a "Try Dart in your browser" link just below the video. When clicked it will hide the video and swap in a DartPad editor. There's no way to swap the video back in, but given that it's a short one on a loop I'm assuming no one would want to. My CSS-fu is such that I don't know how to maintain the height of that row, so there's an unfortunate shift in content when the change is made.

Personally, I prefer the simplicity of layout #3 (DartPad in the middle), but I'm curious what other feedback you (or anyone else) has.

**Comment by kwalrath** [comment]
> There's a "Try Dart in your browser" link just below the video. When clicked it will hide the video and swap in a DartPad editor. 

I totally missed that, as my window was just not quite high enough. I think I expected the text to be a button (or other control) just above or below the video, without the “Dart is a …” words in between.

For all 3, I expected the Try Dart link at the top of the page to switch to the homepage’s embedded DartPad, instead of going to dartpad.dev. (I assume that’s an easy change.) 

Finally, it should be easy to go from the embedded DartPad to dartpad.dev. Can we add that feature back to DartPad (as an option, at least)? 

> Personally, I prefer the simplicity of layout #3 (DartPad in the middle), but I'm curious what other feedback you (or anyone else) has.

I’d love to be able to have DartPad at the top of the page, but I’ll ask our designer and other folks.

**Comment by kwalrath** [comment]
I'm closing this in favor of #1805.

**Pull request closed without merging**
