### PR TITLE
Update pub get troubleshoot documentation

### PR DESCRIPTION
**Pull request by fioan89**
To include proxy configuration steps for
Windows PowerShell.

Change-Id: Ie9afbe574b54789dc18afea1a5bf110a977f4e25

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks, @fioan89!

@legalcodes could you please review this, since you know more about Windows than I do?

**Comment by legalcodes** [comment]
I've created an issue for the terminal command code fencing we should be using:
https://github.com/dart-lang/site-www/issues/1868

**Comment by fioan89** [comment]
Thx. Should I update all command fencing in the troubleshoot section in this PR? Or is it acceptable as is?

**Comment by legalcodes** [comment]
We should handle command fencing across dart.dev in a separate PR. Thanks again!

**Pull request merged**
