### PR TITLE
Updating examples for "DON'T use `async` when it has no useful effect."

### PR DESCRIPTION
**Pull request by lucyget**
Updating examples for "DON'T use `async` when it has no useful effect." to follow "DO use `Future<void>` as the return type of asynchronous members that do not produce values."

### CODE REVIEW

**Comment by kwalrath** [comment]
Thank you, @lucyget!

@munificent, if you like these changes, @lucyget or I can figure out why there are branch conflicts, and I can make sure the build works.

**Comment by kwalrath** [comment]
Paging @munificent...

**Comment by munificent** [comment]
Sorry for the delay! Yes, these changes LGTM.

**Comment by kwalrath** [comment]
I think the merge issue had something to do with the prettify tags: `{% prettify dart tag=pre+code %}` Strangely, Travis doesn't seem to be trying to build this, but I think it'll commit ok. I'll do a little local test and then merge.

**Pull request merged**
