### PR TITLE
add extension to list of keywords

### LINKED ISSUE #2357: Add "extension" to keywords table in language tour
We should add "extension" to the list of [keywords in the language tour](https://dart.dev/guides/language/language-tour#keywords)

cc: @kwalrath

### PR DESCRIPTION
**Pull request by johnpryan**
fixes #2357

### CODE REVIEW

**Comment by johnpryan** [comment]
I _think_ this is considered a contextual keyword since identifiers can be named "extension", so I added that annotation

**Comment by kwalrath** [comment]
Staged: https://dartlang-org-staging-1.firebaseapp.com/guides/language/language-tour#keywords

/cc @leafpetersen in case "contextual keyword" is incorrect... but I'm pretty sure it's correct.

**Comment by leafpetersen** [comment]
No, `extension` is a built-in identifier.  See https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#syntax .

cc @eernstg @lrhn

**Comment by kwalrath** [comment]
Thanks, @leafpetersen. I'll make that fix.

**Pull request merged**
