### PR TITLE
Add link reference checker tool

### PR DESCRIPTION
**Pull request by parlough**
Introduces a link reference checker tool, mostly copied over from `flutter/website`. This eventually will likely go in `site-shared`, but I want to include it here to understand dart.dev's uses over time first.

It fails if there are broken link references in the generated HTML, such as `[webdev][]`, so that missing or broken Markdown definitions are caught before a PR lands.

Also fixes the broken link references it found :D

Fixes https://github.com/dart-lang/site-www/issues/4677
Fixes https://github.com/dart-lang/site-www/issues/4901

### CODE REVIEW

**Comment by MaryaBelanger** [comment]
Can you explain how this is different than `tool/check-links.sh`? Not that I've ever found it to accomplish much, but I thought  the basic purpose of it was kind of what you're describing here.

**Comment by MaryaBelanger** [comment]
Got it, this is really useful!

**Review by MaryaBelanger — APPROVED** [review]

**Comment by MaryaBelanger** [comment]
Not urgent because I checked manually, but I'm wondering how to read this output from the new tool (I'm guessing?) The errors are pointing to the `check_link_references.dart`, I'm not sure if that means that it found anything broken. 

```
Resolving dependencies... 
  _fe_analyzer_shared 60.0.0 (61.0.0 available)
  analyzer 5.12.0 (5.13.0 available)
  build_runner_core 7.2.8 (7.2.9 available)
  built_value 8.5.0 (8.6.1 available)
  code_builder 4.4.0 (4.5.0 available)
  collection 1.17.1 (1.17.2 available)
  csslib 0.17.2 (0.17.3 available)
  file 6.1.4 (7.0.0 available)
  glob 2.1.1 (2.1.2 available)
  graphs 2.3.0 (2.3.1 available)
  lints 2.1.0 (2.1.1 available)
  logging 1.1.1 (1.2.0 available)
  matcher 0.12.15 (0.12.16 available)
  test_api 0.5.2 (0.6.0 available)
  watcher 1.0.2 (1.1.0 available)
Got dependencies!
Checking for valid link references...
tool/check_link_references.dart:3:8: Error: Error when reading '/Users/mbelanger/.pub-cache/hosted/pub.dev/path-1.8.3/lib/path.dart': No such file or directory
import 'package:path/path.dart' as path;
       ^
tool/check_link_references.dart:87:26: Error: Method not found: 'extension'.
      .where((p) => path.extension(p) == '.html')) {
                         ^^^^^^^^^
tool/check_link_references.dart:91:30: Error: Method not found: 'relative'.
      invalidReferences[path.relative(filePath, from: directory)] = results;
                             ^^^^^^^^
```

**Comment by parlough** [comment]
I think I need to clean up the various pubspec files. How did you run the command?

**Comment by MaryaBelanger** [comment]
`make run` then `tool/check-links.sh`. But I was wondering if that's even the appropriate command anymore

**Comment by parlough** [comment]
Yeah I may have added the dependencies to the wrong location. Can you create an issue and assign me? I'll take a look tonight or tomorrow.

**Pull request merged**
