### PR TITLE
Introduce a new footer with social buttons

### PR DESCRIPTION
**Pull request by parlough**
Introduces a new footer to all website pages:

- Includes the Dart lockup logo
- Includes social links (Blog, GitHub, Twitter)
- Expands on licenses of content (still include CC-BY-4.0 but also mentions how code snippets are BSD-3 Clause)
- Improves hover/focus styles to be more noticeable
- Adds titles to the links to provide more context
- Has custom style modifications for narrower displays (instead of just some icons floating over to the next row like we have currently)

Fixes https://github.com/dart-lang/site-www/issues/256

**Staged _(see multiple page bottoms)_:** https://dart-dev--pr4054-feature-new-site-foo-mq98g2cw.web.app/

**Wide:**

New wide footer

**Narrow _(or mobile)_:**

New narrow footer

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by mit-mit** [comment]
Looks neat!

What's the goal of the 'Build' link?

**Comment by sfshaza2** [comment]
That looks quite nice! LGTM

**Comment by parlough** [comment]
@mit-mit The goal was to maintain some information about the build (on hover), but after thinking about it more it doesn't really fit with this new footer and isn't relevant to most users of the site.

I've removed it for now and will explore potential other solutions for surfacing that information when I work on https://github.com/dart-lang/site-www/issues/2938.

**Review by johnpryan — APPROVED** [review]

**Comment by johnpryan** [comment]
Not something introduced by this PR, but the whitespace above the footer on the `index.html` page doesn't look right:

Screen Shot 2022-05-23 at 9 29 04 AM

**Comment by parlough** [comment]
Sure I'll figure something out :)

**Comment by parlough** [comment]
@mit-mit Does this seem fine to merge to you?

**Pull request merged**
