### PR TITLE
Update functions.md

### LINKED ISSUE #5901: Add section on Function type declarations to 'Functions' page
### Page URL

https://dart.dev/language/functions/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/functions.md

### Describe the problem

The [functions page](https://dart.dev/language/functions) doesn't explain `Function` type declarations.

In contrast, the [records page](https://dart.dev/language/records) does explain [record types](https://dart.dev/language/records#record-types) for example.

### Expected fix

Add some explanation about how to use `Function` type declarations. (Including defining return types, parameter types, etc).

It might also be worth mentioning Function types on the [built-in types page](https://dart.dev/language/built-in-types).

### Additional context

_No response_

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

### PR DESCRIPTION
**Pull request by RikinR**
added the " Function type " section in the file

Added the Function types section similar to one in Record file . 

Fixes #5901

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn't contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn't use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Comment by MaryaBelanger** [comment]
This looks great, thanks so much @RikinR! I'm going to pull your PR locally to fix the test failure and make some minor additions (I'll leave a comment afterwards explaining what I changed and why, so you can do the same for your future PRs 😄)

**Comment by RikinR** [comment]
okay thanks !

**Comment by MaryaBelanger** [comment]
@RikinR The test failure was because of the code excerpt failing (happens all the time, no worries).

We have a system where the code blocks we use for examples in markdown files correspond to actual Dart files (in the `/examples` directory) so that the code is actually tested and kept up to date. 

So I added your code example [to the `functions.dart` file](https://github.com/dart-lang/site-www/pull/5944/commits/2f51f37503b9412243a85148b3144da057b132ce#diff-73a37539c25c3c0953ea52a17b1244c6dfdc56676aba6fcee56a372381bf1ef6R30-R33), and enclosed it with `// #docregion ... // #enddocregion` comments. The name of that docregion (`function-type`) goes in the parenthesis at the end of the  `<?code-excerpt ...` tag in the `functions.md` file ([line 212](https://github.com/dart-lang/site-www/pull/5944/commits/2f51f37503b9412243a85148b3144da057b132ce#diff-89a231955f5d4a67f0ad66d8fc109e124445471bdc23f4bd39e0375710df09e2R212)).

And then, finally, after you do all that, you have to run the command `./dash_site refresh-excerpts` (you can read more about that [here](https://github.com/dart-lang/site-www?tab=readme-ov-file#refresh-code-excerpts)). That's all, hope that helps with your next contribution!

---

I made a couple other minor changes in this commit too, if you'd like to know why:
- We try to keep lines under 80 characters to make it easier to read/review the markdown, so I broke up your paragraphs into new lines at punctuation marks or where they hit 80.
- You used an html `<code>` tag inline in one of your paragraphs, but we normally just use backticks (`) to do code font (again, makes the markdown easier to read)
- I moved your entire new section below the function parameters section, because the definition of "function types" is based on parameters so I thought that made more sense.

We're almost done! I'm going to review/edit the actual contents of your PR now, and then we'll get this merged 🤞 Thanks again!

**Comment by mmcdon20** [comment]
I'm confused by the following:

> In Dart, function types can be _explicitly_ declared based on context. 

What does this mean? What context? 

> Here is an example of declaring function types:
> 
> ```dart
> int add(int a, int b) => a + b;
> // int function(int, int) = add;
> ```

But the above example doesn't declare a function type. There is a function declaration, and a comment, but no function type declaration. The comment sort of looks like a function type declaration but the syntax is wrong. The type of `int add(int a, int b) => a + b;` is `int Function(int, int)` (note the capital F in Function). This means you can assign `add` to a variable of type `int Function(int, int)`, ie `int Function(int, int) myVariable = add;`, or you can pass `add` to a function or method that accepts an `int Function(int, int)` as an argument, ie  `[1, 2, 3, 4, 5].reduce(add)`, etc.

> When you declare functions, you can specify the type of function,

You declare a function type when you want to store a function in a variable, accept a function as an argument to a function, return a function from a function, ie the same places you would declare any other type such as `int`, or `String` etc.

> which indicates that the return value from the function should be of that specific type.

The return type is part of it, but a function type declaration describes the entire signature of a function, which in dart can include:

* The return type
* The types for each of the positional parameters
* The types and names of each named parameter (and if they are required)
* Any generic type arguments and their restrictions

To give a more complex example, which illustrates the above, the following function definition:

```dart
T lookupAtN<T extends Object>(List<T> elements, {required int n}) => elements[n];
```

Has the following type

```dart
T Function<T extends Object>(List<T>, {required int n})
```

Therefore I can define a variable of the above type and assign `lookupAtN` to the variable.

```dart
T Function<T extends Object>(List<T>, {required int n}) myVariable = lookupAtN;
```

---

Also it might be worth linking to this from [built-in types page](https://dart.dev/language/built-in-types), as I mentioned in the original issue.

**Comment by RikinR** [comment]
@mmcdon20 . Thanks for correcting . I do get your your point , you were talking about "Function Type" declaration for a variable and what I did was declared a function . So should I mention this "Function Type" directly to [built-in-types-page](https://dart.dev/language/built-in-types)  ?

**Comment by eernstg** [comment]
Drive-by comment: The section about 'Function types' might be a better fit right after the section 'Functions as first-class objects': First-class function objects can be assigned to variables and passed as actual arguments to function invocations, and it makes sense for those variables and parameters to have a declared type which is a function type. If we don't have first-class function objects then we would never be able to use a function type because there are no values that said type could be the type of.

(OK, we could still write `void Function()? x = null;`, but there would be no non-silly way to use a function type ;-)

We could then have something along these lines:

## Function types

We can specify the type of a function, which is known as a _function type_.
It is actually the type of a first-class function object: An expression whose
type is a function type can only evaluate to a first-class function object.
A function type is obtained from a function declaration header by replacing
the function name by the word `Function`. Moreover, we are allowed to omit
the names of positional parameters, but the names of named parameters
cannot be omitted. For example:

<?code-excerpt "misc/lib/language_tour/functions.dart (function-type)"?>
```dart
void printElement(int element) => print(element);

void doPrint(void Function(int) printFunction, {required List<int> list}) {
  list.forEach(printFunction);
}

var list = [1, 2, 3];

// Store `doPrint` in a variable and call it.
void Function(void Function(int), {required List<int> list}) g = doPrint;
g(printElement, list: list);
```

**Comment by mmcdon20** [comment]
> So should I mention this "Function Type" directly to [built-in-types-page](https://dart.dev/language/built-in-types) ?

I think just a link in the bulleted list should be enough here. Same thing is done for Records.

**Comment by sfshaza2** [comment]
@eernstg, Marya is out on leave. Can I approve and land this PR?

**Comment by mmcdon20** [comment]
@sfshaza2 The PR hasn't been updated to account for the feedback. 
I think the following changes should be made:

1. The explanation of function types should be closer to what @eernstg wrote (I would be fine with Erik's explanation as is). 
2. The 'Function types' section should be moved to after the 'Functions as first-class objects' section.
3. Add a link to function types in the bulleted list at the top of [built in types page](https://dart.dev/language/built-in-types) just like it is for record types.

**Comment by RedBrogdon** [comment]
Hey, @RikinR, it looks like you haven't had time to get back to this PR in a while. Could you let us know (ideally in the next day or so) if you're still planning to do so? Otherwise we can move forward with #6037.

**Comment by RikinR** [comment]
hey sorry ! actually I am moving abroad this month thus I will not be able to work on this issue. Sorry for the inconvenience . hope you understand

**Comment by RedBrogdon** [comment]
> hey sorry ! actually I am moving abroad this month thus I will not be able to work on this issue. Sorry for the inconvenience . hope you understand

Life happens. I'll close the PR. In the meantime, I hope you enjoy your new home!

**Pull request closed without merging**
