### PR TITLE
update dart-devtools.md to use new `dart` tool

### PR DESCRIPTION
**Pull request by woinbo**
Update the dart-dev tools in
src/tools/ to use the new `dart` tool

### CODE REVIEW

**Review by kwalrath — COMMENTED** [review]
Changes look good! Could you also test & update references to `dart --observe` in this page?

**Comment by woinbo** [comment]
@kwalrath ok sure , sorry the late reply, this happens because of time zone as I reside in India and here it's night while their day in San Francisco

**Comment by woinbo** [comment]
Hello @kwalrath, I just checked and tested dart --observe everything is working fine. Then what's needed to be updated??

**Comment by kwalrath** [comment]
> Hello @kwalrath, I just checked and tested dart --observe everything is working fine. Then what's needed to be updated??

We don't want people using just `dart` to run things any more, so the command should probably be `dart run --observe`.

**Comment by woinbo** [comment]
@kwalrath please review now, it this okk.. or anything else to be done

**Review by kwalrath — APPROVED** [review]

**Comment by kwalrath** [comment]
Thanks, @woinbo!

**Comment by woinbo** [comment]
😍 Thank you @kwalrath this was my first PR and it got merged. Really feeling goosebumps. @kwalrath do consider me for other issues on dart/flutter/docs. I would also like to show time will dart/flutter participate in GSoC 2021 or not?
Thanks again for this PR 🥰

**Comment by kwalrath** [comment]
Congrats, @woinbo! I don't know what our plans are for GSoC, although we [did participate in GSoC 2020](https://medium.com/dartlang/google-summer-of-code-2020-results-a38cd072c9fe). With null safety and Flutter event work, everybody in Dart/Flutter developer relations is really busy right now. Another thing on the doc side is thinking about recommendations for package READMEs... I should create an issue to gather people's feedback.

**Pull request merged**
