### PR TITLE
mark before_release script as executable

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Deploy didn't work - https://github.com/dart-lang/site-www/runs/4806423246?check_suite_focus=true#step:11:17

Try try try again!

**Comment by kwalrath** [comment]
lgtm, thanks for watching this

**Comment by kwalrath** [comment]
It worked!

image

**Comment by parlough** [comment]
Thanks for catching this!

**Pull request merged**
