### PR TITLE
Add website staging GCB template

### PR DESCRIPTION
**Pull request by drewroengoogle**
* Adds a GCB template that is responsible for building the website and staging it to firebase in PRs
* Once the website is built, `dart-github-bot` will comment in the PR a link that you can navigate to in order to see your changes.
* After this template is merged in, we can update the PR trigger to run this template on all PRs. It is currently disabled in order to ensure that it is not run on branches without this template in it yet.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
- [x] This PR doesn’t contain automatically generated corrections or text (Grammarly, LLMs, and similar).
- [x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style) — for example, it doesn’t use _i.e._ or _e.g._, and it avoids _I_ and _we_ (first person).
- [x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks) of 80 characters or fewer.

<details>
  <summary>Contribution guidelines:</summary><br>

  - See our [contributor guide](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md) for general expectations for PRs.
  - Larger or significant changes should be discussed in an issue before creating a PR.
  - Code changes should generally follow the [Dart style guide](https://dart.dev/effective-dart) and use `dart format`.
  - Updates to [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) indicated by `<?code-excerpt` need to be updated in their source `.dart` file as well.
</details>

### CODE REVIEW

**Review by khanhnwin — APPROVED** [review]

**Comment by drewroengoogle** [comment]
@parlough This is the same as the change made to the flutter docs site!

**Comment by parlough** [comment]
Thanks so much for working on this @drewroengoogle! Will be nice to get in. I'll take a look tomorrow morning.

There is one blocking issue though...

You need to give @dart-github-bot a proper icon! Something Dart or Dash related. I bet @khanhnwin has a big collection if you don't have anything in mind. 😄

**Comment by drewroengoogle** [comment]
> Thanks so much for working on this @drewroengoogle! Will be nice to get in. I'll take a look tomorrow.
> 
> There is one blocking issue though...
> 
> You need to give @dart-github-bot a proper icon! Something Dart or Dash related. I bet @khanhnwin has a big collection if you don't have anything in mind. 😄

Khanh helped find a couple shiny new profile photos for the dart and flutter bots!

**Comment by khanhnwin** [comment]
@parlough you know me too well haha Always happy to provide cute graphics :)

**Review by parlough — APPROVED** [review]
Thank you both!!

**Pull request merged**
