### PR TITLE
Update code color

### PR DESCRIPTION
**Pull request by dhanushuUzumaki**
Contributes to #1929

### CODE REVIEW

**Comment by chalin** [comment]
Hi @dhanushuUzumaki. Thanks for the fix!

It is customary to put the issue number in the PR comment rather than in the title, for example, something like this: Closes #1929. In this way GitHub will automatically close the corresponding issue when the PR is merged.

**Comment by chalin** [comment]
Have you generated the site locally to ensure that the color update works?

**Comment by dhanushuUzumaki** [comment]
> Hi @dhanushuUzumaki. Thanks for the fix!
> 
> It is customary to put the issue number in the PR comment rather than in the title, for example, something like this: Closes #1929. In this way GitHub will automatically close the corresponding issue when the PR is merged.

Sure @chalin Will use this format from next time.

**Comment by dhanushuUzumaki** [comment]
> But the code font is still red; for example the "bin" in "Homebrew bin directory...".

Sorry, My bad. Have trouble with colors. But found the issue.

https://github.com/dart-lang/site-www/blob/e61fa47052b910aed9eadcf86795f7444a8613de/src/_assets/css/main.scss#L214 needs to be changed. Changing this seems to do the trick. However, if I use $color-code variable, it gets the value of #4A4A4A due to this line https://github.com/dart-lang/site-shared/blob/8f783bfa10019afb023d4917f9cd8e614227bd3d/src/_assets/css/_bootstrap_config.scss#L7

Should I use the hex value instead of the variable?

**Comment by dhanushuUzumaki** [comment]
Using $color-code variable

image

Using hex value directly

image

**Comment by chalin** [comment]
There is something wrong with the SCSS overrides that I'll fix in a followup PR.

In the meantime, I suggest that you:
- Use the `$code-color` variable in the definition of `code` in `main.scss`.
- Still in `main.scss`, right after the declaration of `$code-weight: 400;`, repeat the declaration of `$code-color` (duplicate it from `_variables`), and add a comment to say that this is a temporary fix: `// Temporary fix`.

Regenerate the site (delete all site-generated files), and ensure that the color is updated as it should be. Thanks.

**Comment by dhanushuUzumaki** [comment]
@chalin Made the changes and I can see the new color.

image

**Comment by chalin** [comment]
Great, thanks!

**Pull request merged**
