### PR TITLE
Improve good/bad code snippet legibility

### LINKED ISSUE #1093: Background color for neutral code snippets is too similar to bad one
More info: https://github.com/dart-lang/site-www/pull/1050

And the original report:

> For example, code snippets under https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-listfrom-unless-you-intend-to-change-the-type-of-the-result looks to have similar background color as the code snippets annotated as "bad".
> 
> I was wondering why this code was bad, and only after careful inspection, realized that the "bad" from the top-right corner was missing. Consider using a background color that is different from the "bad" and "good" snippets .
>

### PR DESCRIPTION
**Pull request by laurameck**
Fixes #1093
Screen Shot 2020-10-02 at 9 33 50 PM

### CODE REVIEW

**Comment by laurameck** [comment]
@chalin @kwalrath Marked as ready for review now that @tijoforyou signed off on the change :)

**Comment by kwalrath** [comment]
Adding @mit-mit, since he's doing some legibility-related work

**Review by kwalrath — COMMENTED** [review]
Looks great to me. Thank you, @laurameck!

I'll let @mit-mit have the final say, since he's working on #2658.

**Comment by mit-mit** [comment]
lgtm

**Review by mit-mit — APPROVED** [review]

**Comment by mit-mit** [comment]
Thanks @laurameck for the contribution!

**Pull request merged**
