### PR TITLE
removed retype() method from Stream class

### PR DESCRIPTION
**Pull request by iChicago**
Hello, 
This is a fix for this issue 
https://github.com/dart-lang/site-www/issues/1922

### CODE REVIEW

**Comment by kwalrath** [comment]
Good catch, thanks for the fix!

I'm going to investigate why the build failed before I commit this, but I don't think your change was the culprit.

**Comment by chalin** [comment]
> I'm going to investigate why the build failed ...

As you probably noticed already, the change needed to be done in the originating source file: `misc/lib/tutorial/stream_interface.dart`.

**Comment by kwalrath** [comment]
> > I'm going to investigate why the build failed ...
> 
> As you probably noticed already, the change needed to be done in the originating source file: `misc/lib/tutorial/stream_interface.dart`.

Nope, I did NOT notice. I thought it was just a plain old list. I'll fix the build. Thanks, @chalin!

**Comment by chalin** [comment]
That source file can probably be tweaked to ensure that the analyzer catches errors like the one fixed by this PR (a method removed from an API). I'm not sure if it is worth it though.

**Comment by kwalrath** [comment]
> That source file can probably be tweaked to ensure that the analyzer catches errors like the one fixed by this PR (a method removed from an API). I'm not sure if it is worth it though.

Were you thinking of `@override` annotations? I thought about that but then figured that, like you said, it wasn't worth the trouble for an API that's been so stable (with this one exception).

**Comment by chalin** [comment]
> Were you thinking of `@override` annotations?

Yes.

> ... [not] worth the trouble for an API that's been so stable

Agreed.

**Pull request merged**
