### PR TITLE
Update who-uses-dart.md

### PR DESCRIPTION
**Pull request by rafbermudez**

### CODE REVIEW

**Comment by kwalrath** [comment]
Happy to accept this once the CLA is signed.

**Comment by filiph** [comment]
Hi @rafbermudez, we need you to sign the CLA, then reply to this thread with "I signed it". We cannot accept PRs without a CLA, unfortunately.

**Comment by kwalrath** [comment]
I'm going to close this, since we haven't heard from @rafbermudez. However, we'd be happy to take the change once the CLA is signed.

**Comment by rafbermudez** [comment]
I signed it! Excuse the wait

**Comment by kwalrath** [comment]
Thanks! Your changes should be visible in a few minutes.

**Pull request merged**
