### PR TITLE
Update list range error in patterns.md code excerpt

### PR DESCRIPTION
**Pull request by msarkrish**
List has 2 values but code snippet is accessing second index of the list.

### CODE REVIEW

**Review by MaryaBelanger — APPROVED** [review]
Thank you for catching that!

**Comment by msarkrish** [comment]
> CI isn't passing because the code is part of a code excerpt that needs to be refreshed, I believe. 

Hi MaryaBelanger, 
Is there anything I have to do?

**Comment by MaryaBelanger** [comment]
Hi @msarkrish , sure you can try to add the code excerpt yourself. I _think_ you need Docker set up (info in the readme for this repo).

On [line 320](https://github.com/dart-lang/site-www/pull/4879/files#diff-8b29e31be27df683f382843a6ecf218cdb34ae095ecdf6bf26dd308d7ed669cdL320), you can see the code excerpt tag: `<?code-excerpt "language/lib/patterns/json.dart (json-2)"?>`

This tells you that the code excerpt is in [`examples/language/lib/patterns/json.dart`](https://github.com/dart-lang/site-www/blob/main/examples/language/lib/patterns/json.dart) and that it's in the `docregion` named `json-2`, which you'll find on [line 13](https://github.com/dart-lang/site-www/blob/main/examples/language/lib/patterns/json.dart#L13) of that file.

So you need to make the same changes you made in `patterns.md` there. Then save it, and (you need docker for this part) run the [Pre-push site checks](https://github.com/dart-lang/site-www#pre-push-site-checks), specifically:

```
// docker is up and running
make run

// this makes sure the .dart code corresponds to the code in the .md file
tool/refresh-code-excerpts.sh

// this checks everything in the codebase for errors
tool/test.sh
```

The last command will take a few minutes to run, and you'll have to scroll back up through the output once it's done and scan it closely to see if your code excerpt caused any issues. There are usually warnings for a handful of other code excerpts, so just make sure you check for yours. If you're not sure or can't tell, just push you commit at this point and the CI will let us know anyway.

**If you don't have docker set up**, or can't get it to work, it _might_ be sufficient to update the code excerpt dart file to match the code you already changed in the md, save it and then push your changes here without running any of the tools yourself. The CI that is failing here also runs `tool/test.sh` so that'll let us know if it's possible or not. 

Good luck! Let us know if you have any problems

**Comment by MaryaBelanger** [comment]
Actually @msarkrish, I can take care of everything I described in my last comment! So don't worry about anything else; this will be ready to merge soon :)

**Comment by MaryaBelanger** [comment]
FYI @msarkrish, the nullable access operator isn't needed here. `user is List<dynamic>` promotes it to non-nullable.

Thanks again!

**Comment by msarkrish** [comment]
Thank you @MaryaBelanger . Actually I had a plan of doing this in the coming weekend. I have tried that code with DartPad, It shows error. That's why I have added null check added. Correct me, If I missed something.
image

**Comment by parlough** [comment]
Ah, thanks for pointing that out @msarkrish! Our code excerpt was relying on a different local `json`, resulting in different type promotion due to a [subtype mismatch](https://dart.dev/tools/non-promotion-reasons#subtype-mismatch). 

I'll adjust the code to make it a bit more generic - https://github.com/dart-lang/site-www/pull/4902

**Comment by msarkrish** [comment]
Oh, Thank you @parlough

**Comment by parlough** [comment]
Thank you!!

**Pull request merged**
