### PR TITLE
Short-link for dart.dev/go/downgrade-testing

### PR DESCRIPTION
**Pull request by jonasfj**
For use in pana output on pub.dev (scoring page)

image

### CODE REVIEW

**Comment by jonasfj** [comment]
Blocked until https://github.com/dart-lang/site-www/pull/5838 lands.

**Review by sigurdm — APPROVED** [review]

**Review by parlough — APPROVED** [review]
Thanks! Feel free to land when ready.

Optionally, do consider something like `/go/pub-downgrade-testing` or `/go/package-downgrade-testing` to make it more clear it's about package versions rather than SDK versions.

**Comment by jonasfj** [comment]
I don't mind using either:
 * `/go/pub-downgrade-testing` or,
 * `/go/package-downgrade-testing`

But:
 * (A) I think when we present the link to the user, in the context of a pana report about downgrade testing, `pub-` or `package-` is going to be unnecessary. It'll be clear to the user that we're talking about something to do with packages. So from that perspective I don't think we need it.
 * (B) I don't think that there is a huge risk we'll end up conflicting with other future go-links.

So all we'd do is making the short-link longer :rofl:

**Comment by parlough** [comment]
Makes sense! Keeping the shorter link works for me :)

**Review by MaryaBelanger — APPROVED** [review]

**Comment by MaryaBelanger** [comment]
@atsansone this was dependent on another PR (the section doesn't exist yet) as stated in an earlier [comment](https://github.com/dart-lang/site-www/pull/5872#issuecomment-2133349575)

**Pull request merged**
