### PR TITLE
[Effective Dart] Update tear-off rule to mention constructor tear-offs.

### LINKED ISSUE #3560: Mention constructor tear-offs in Effective Dart "DON’T create a lambda when a tear-off will do."
### Page URL

https://dart.dev/guides/language/effective-dart/usage#dont-create-a-lambda-when-a-tear-off-will-do

### Describe the problem

We have an existing rule that tells users to use a tear-off when possible. Right now, it is worded to specifically refer to methods. The language is getting support for [constructor tear-offs](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) soon, so we should reword this guideline to include those too.

### PR DESCRIPTION
**Pull request by munificent**
Fix #3560.

### CODE REVIEW

**Review by parlough — APPROVED** [review]
All these examples and the new explanation look good to me. 

_That is assuming we are planning to wait until this is released to stable though. If not, we will have to make some minor infrastructure changes/exceptions._

**Comment by domesticmouse** [comment]
Looks like we need to enable language features?

```
line 176, column 46 of examples/misc/lib/effective_dart/usage_good.dart: This requires the 'constructor-tearoffs' language feature to be enabled.
      ╷
  176 │     var buffers = charCodes.map(StringBuffer.new);
      │                                              ^^^
      ╵
```
context: https://github.com/dart-lang/site-www/runs/4075320288?check_suite_focus=true#step:10:28

**Comment by munificent** [comment]
> That is assuming we are planning to wait until this is released to stable though. If not, we will have to make some minor infrastructure changes/exceptions.

I'm personally agnostic about when this lands. I sent a PR out because fixing the issue is part of the [constructor tear-offs project](https://github.com/orgs/dart-lang/projects/27). If there's a way to get it building now by enabling the language feature, I'm happy to do that. Otherwise, I'm happy to wait until constructor tear-offs ship. Just let me know how to proceed. :)

**Comment by kwalrath** [comment]
Let's hold off on merging this until constructor tear-offs ship in stable

**Comment by kwalrath** [comment]
fyi @craiglabenz here's the Effective Dart change for constructor tear-offs

**Review by kwalrath — APPROVED** [review]

**Comment by mit-mit** [comment]
Merging now that 2.15 is out

**Pull request merged**
