### PR TITLE
make header background color match the image

### PR DESCRIPTION
**Pull request by johnpryan**
context: https://github.com/dart-lang/site-www/pull/1565#discussion_r281289148

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks, John. I'll stage this so the designer can take a look.

**Comment by mit-mit** [comment]
@kwalrath is this in https://dartlang-org-staging-0.firebaseapp.com/? I still see the color difference there...

**Comment by kwalrath** [comment]
> @kwalrath is this in https://dartlang-org-staging-0.firebaseapp.com/? I still see the color difference there...

That's the master version. The staged version of John's fix is at https://sz-www-1.firebaseapp.com/

**Comment by mit-mit** [comment]
Yeah, that looks a lot better. I'd just merge this.

**Comment by kwalrath** [comment]
I can't see the difference on my screen, but since you say so... :)

(Btw, I _can_ see code font now, so not all changes are lost on me.)

**Pull request merged**
