### PR TITLE
Advise UpperCamelCase extensions

### PR DESCRIPTION
**Pull request by pq**
/cc @munificent @kwalrath

### CODE REVIEW

**Comment by pq** [comment]
Not quite sure how to fix the breakage.  When I follow the advise from travis I hit this snag:

```
[~/src/repos/site-www] (master) $ tool/refresh-code-excerpts.sh
/Users/pq/src/repos/site-www/tool/env-set.sh: line 3: tool/shared/env-set.sh: No such file or directory
```

(and indeed I don't see `env-set.sh`...)

**Comment by kwalrath** [comment]
I'll take a look...

**Comment by pq** [comment]
Thanks!

**Comment by kwalrath** [comment]
There are a couple of things going on. The first is that there's no corresponding change in examples/misc/lib/effective_dart/style_good.dart. Once you add it, I think you run into the issue that the stable channel doesn't support `extension` yet.

**Comment by kwalrath** [comment]
Let's let this sit a little bit... @munificent feel free to review the words and code. When we're ready to publish 2.5-related stuff (whether on dev or in stable), then I'll make this work.

**Comment by pq** [comment]
Sounds good.  I added the 2.5 milestone.  Let me know if I should do anything else.

Thanks!

**Comment by kwalrath** [comment]
It looks like even the dev channel (2.5.0-dev.2.1) doesn't support extension yet.

**Comment by pq** [comment]
Yeah.  At current, you need to enable the experiment (either w/ a command line flag or analysis option).

**Comment by kwalrath** [comment]
To make the build pass, we need to (1) support extension methods (so... not yet) and (2) update the examples directory to contain the code we import into the page. I've done the latter. We'll have to wait on this PR until we have an SDK version that supports the former.

**Comment by kwalrath** [comment]
The dev build is happier now. Analyzer messages have changed, so the dev build is still failing, but that's a known issue. (#1894)

**Comment by kwalrath** [comment]
I think we're ready to publish. Agreed, @pq?

Staged: https://kw-www-dartlang-1.firebaseapp.com/guides/language/effective-dart/style#do-name-extensions-using-uppercamelcase

**Comment by pq** [comment]
Agreed.  Thanks!

**Pull request merged**
