### PR TITLE
fix to appengine package link

### PR DESCRIPTION
**Pull request by lambdaR**
hovering the mouse over 'appengine package' only affects 'package'.

### CODE REVIEW

**Comment by lambdaR** [comment]
@googlebot I signed it!

**Comment by parlough** [comment]
Hey @lambdaR! Thanks for the pull request :)

It seems intentional that the "inline code" style was used for `appengine` as it is a package that can be utilized and imported, so perhaps the issue is that we instead need to introduce a hover style for links that are inline code(`a code`). What do you think?

**Comment by lambdaR** [comment]
@parlough  probably, or maybe it is better to exclude `appengine` from the link, i just did a PR.
also, there is a subtle difference of what you see in github preview and the actual web site https://dart.dev/server/google-cloud regarding the "inline code"

**Comment by lambdaR** [comment]
there must be a better way to do this ... anyway happy I/O

**Comment by kwalrath** [comment]
> there must be a better way to do this ... anyway happy I/O

I hope you've been enjoying I/O!

**Pull request closed without merging**
